"""The avatar: the one moving entity in the observatory. Layer 1 (scene/USD).

Structure built (all paths under the REAL stage root ``/Root`` -- there is no
``/World`` on this stage; confirmed in the GUI 2026-08-15)::

    /Root/Avatar                    Xform, identity, never moves
      +-- Looks/avatar_skin         UsdPreviewSurface + non-visual "skin"
      +-- body_mesh                 Capsule -- collision. PhysX moves this one.
      |     |                       INVISIBLE: it collides, it does not render.
      |     +-- cam_first_person    eye height, looks along travel
      |     +-- cam_third_person    3 m behind, 1.6 m up, pitched down 25 deg
      +-- character                 what you SEE: the warehouse's rigged Worker,
      |     +-- rig                 referenced. Follows body_mesh via the graph.
      +-- Controls                  OmniGraph: character controller + the follow

Why the cameras hang off ``body_mesh`` and not off ``/Root/Avatar``
-------------------------------------------------------------------
Physics moves the *capsule*, not its parent. Cameras parented to the Xform
would stay behind while the body walked away -- a silent failure of exactly the
kind this project keeps a list of. They are still descendants of the Avatar
Xform, switching view is still just rebinding the viewport, and nothing ever
drives a camera directly. ``/Root/Avatar`` is deliberately left at identity:
the character controller writes a *world* pose back onto the capsule, so a
non-identity parent would teleport the avatar on the first simulated frame.

Why a PhysX character controller and not a kinematic rigid body
----------------------------------------------------------------
The gate for this task is "walking into a shelf stops you". A kinematic rigid
body **cannot** do that: PhysX moves a kinematic actor to its target pose
unconditionally and does not depenetrate it, so it drives straight through
static geometry. Kinematic-vs-static contacts are not even generated by
default. The requirement "kinematic, not dynamic" and the requirement "the
shelf stops you" are not jointly satisfiable by a rigid body.

``PhysxCharacterControllerAPI`` is the resolution and is what the requirement
was reaching for. PhysX implements a CCT *as* a kinematic actor -- the schema's
own doc for ``scaleCoeff`` says "scale coefficient for underlying kinematic
actor" -- so nothing here ragdolls, trips, or falls through a floor. On top of
that it does collide-and-slide against static geometry, which is the half a
kinematic body cannot do.

Two consequences, both deliberate:

  * The capsule carries **no** ``UsdPhysics.CollisionAPI``. A prim with
    CollisionAPI and no rigid body is *static* collision geometry, so applying
    it here would park a static capsule inside the character controller's own
    actor and fight it. The CCT is the collision representation.
  * What ray-based sensors bounce off is **render** geometry, not colliders --
    RTX lidar and radar trace the same BVH the renderer does. So the avatar
    needs a visible mesh for its own sake, and that is ``character``, not the
    capsule. The capsule is hidden with ``visibility = "invisible"`` and keeps
    ``purpose = "default"``; NVIDIA's own CCT demo hides its capsule with
    ``purpose = "guide"`` instead, which is inherited and would take the
    character down with it. ``verify_avatar.py`` asserts both halves: the
    capsule does not render, and the character does.

Execution model
---------------
This script creates prims and saves USD. It reads no sensor data, so exec mode
(see CLAUDE.md) does not apply and ``SimulationApp`` is correct. It does need
Kit running, for the asset resolver and for the OmniGraph node registry.

Reused rather than written (hard rule 4)
----------------------------------------
The control wiring is NVIDIA's, from two shipped examples:

  * ``isaacsim.examples.interactive.omnigraph_keyboard`` -- Isaac Examples ->
    Input Devices -> Omnigraph Keyboard. Read first, as instructed. What it
    actually does: builds an ``omni.graph.action`` execution graph in which
    ``OnTick`` (``onlyPlayback=True``) drives ``ReadKeyboardState`` nodes for
    'A' and 'D', converts their booleans to doubles, negates one, scales the
    sum by 0.1, and read-modify-writes a prim attribute through
    ``ReadPrimAttribute`` -> ``Add`` -> ``WritePrimAttribute``. It resizes a
    cube. The transferable part is the accumulator pattern, not the graph.
  * ``omni.physx.cct`` -> Physics demos -> Character Controller -> "Action
    Graph" (``data/demos/actiongraph.usd``). Same idea, finished: an
    ``OnStageEvent('Simulation Start Play')`` activates an
    ``omni.physx.cct.OgnCharacterController`` node, whose ``setupControls =
    "Auto"`` binds WASD/E/Q and gamepad for us. That is the wiring below, with
    the demo's arrow-key rebinding and its ``purpose="guide"`` capsule dropped,
    and its centimetre-stage numbers converted to metres.

Controls, once you press Play (defaults from
``omni.physxcct.scripts.utils.setup_controls``)::

    W / S   forward / back   (world -X / +X -- MEASURED, not read off the
    A / D   left / right      control code, which looks like it means +X. The
    E / Q   jump / down       controller inverts X and not Y; see _FORWARD_X.
                              Movement is world-axis: it does not follow the
                              view, because the view cannot be turned.)

Run::

    docker compose -f docker/docker-compose.yml run --rm sim \\
        ./python.sh /workspace/sim/avatar.py
"""

from __future__ import annotations

# --- SimulationApp must exist before any omni/pxr/isaacsim import (hard rule 3)
# When this file is imported (S7 wants that), Kit is already up and this block
# is skipped. When it is run as a script, this is the first thing that happens.
if __name__ == "__main__":
    from isaacsim import SimulationApp

    _APP = SimulationApp({"headless": True})
else:
    _APP = None

import argparse  # noqa: E402
import os  # noqa: E402
import sys  # noqa: E402
from pathlib import Path  # noqa: E402

import omni.graph.core as og  # noqa: E402
import omni.usd  # noqa: E402
import yaml  # noqa: E402
from isaacsim.core.experimental.materials import NonVisualMaterial, PreviewSurfaceMaterial  # noqa: E402
from isaacsim.core.experimental.utils.app import enable_extension  # noqa: E402
from isaacsim.core.experimental.utils.semantics import add_labels  # noqa: E402
from pxr import Gf, PhysxSchema, Sdf, Usd, UsdGeom, UsdShade  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
SCENE_YAML = REPO / "config" / "scene.yaml"
BASE_STAGE = REPO / "sim" / "observatory_base.usd"

# The stage this script writes. NOT observatory_base.usd: that file is the
# tracked S5 artifact (6.5 MB, committed at 470ea5d) and the base every later
# task starts from. Overwriting it would make this script destructive and
# non-idempotent, and would put a 6.5 MB binary diff in every avatar tweak.
# The output is a thin layer that SUBLAYERS the base, so it costs a few KB and
# the base stays authoritative. scenes/ is not an option: it is a symlink to
# /ssd1/quang/scenes, which is not mounted into the container.
OUT_STAGE = REPO / "sim" / "observatory_avatar.usd"

# Stage root. Read off the real stage, never invented (hard rule 1).
ROOT = "/Root"


def _paths(avatar_path: str) -> dict[str, str]:
    """Every prim path this module touches, derived from one root."""
    return {
        "avatar": avatar_path,
        "body": f"{avatar_path}/body_mesh",
        "character": f"{avatar_path}/character",
        "rig": f"{avatar_path}/character/rig",
        "cam_fp": f"{avatar_path}/body_mesh/cam_first_person",
        "cam_tp": f"{avatar_path}/body_mesh/cam_third_person",
        "looks": f"{avatar_path}/Looks",
        "material": f"{avatar_path}/Looks/avatar_skin",
        "graph": f"{avatar_path}/Controls",
    }


def load_avatar_config(path: Path = SCENE_YAML) -> dict:
    """The avatar block of config/scene.yaml. The config is the contract."""
    with open(path, encoding="utf-8") as fh:
        return yaml.safe_load(fh)["avatar"]


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
def add_avatar(
    stage: Usd.Stage | None = None,
    *,
    config: dict | None = None,
    spawn_xy: tuple[float, float] | None = None,
    worker_asset: str | None = None,
) -> dict[str, str]:
    """Add the avatar to an already-open stage and return its prim paths.

    Structured this way because S7 needs to drop an avatar into a stage that is
    already open in the GUI, not only into one this script opened.

    Args:
        stage: Target stage. Defaults to the current Kit stage, which is what
            both callers actually have. A stage that is not the current one is
            rejected loudly rather than half-built: the Isaac material and
            semantics helpers resolve against the current stage.
        config: The ``avatar`` block of config/scene.yaml. Read from disk if
            not given.
        worker_asset: USD asset the visible body is referenced from -- the same
            rigged character ``/Root/Worker`` payloads, read off the stage by
            :func:`read_base_facts` rather than written out here. Without it the
            avatar is a bare (invisible) collision capsule.
        spawn_xy: Ground position. Defaults to wherever the warehouse's own
            Worker character is standing -- a spot a human-sized capsule is
            known to fit, read from the stage instead of guessed. A guessed
            coordinate that lands inside a shelf leaves the controller stuck
            with no error.

    Returns:
        The prim paths created, keyed by role.
    """
    ctx = omni.usd.get_context()
    current = ctx.get_stage()
    if stage is None:
        stage = current
    if stage is None:
        raise RuntimeError("no stage is open -- open one before calling add_avatar()")
    if stage != current:
        raise ValueError(
            "add_avatar() only builds into the CURRENT Kit stage; the Isaac "
            "material and semantics helpers resolve against it. Open the "
            "target stage in the usd context first."
        )

    cfg = config or load_avatar_config()
    p = _paths(cfg["prim_path"])

    up_axis = UsdGeom.GetStageUpAxis(stage)
    if up_axis != UsdGeom.Tokens.z:
        raise RuntimeError(
            f"stage up axis is {up_axis!r}; the character controller's movement "
            "code treats index 2 as vertical, so this avatar assumes Z-up"
        )
    if not stage.GetPrimAtPath(ROOT).IsValid():
        raise RuntimeError(f"{ROOT} not found on the stage -- wrong stage?")

    # --- geometry ---------------------------------------------------------
    # height = cylinder + two hemispherical caps, so the cylinder is
    # height - 2*radius and the centre sits half a height off the floor.
    height = float(cfg["height"])
    radius = float(cfg.get("radius", 0.30))
    cyl = height - 2.0 * radius
    if cyl <= 0:
        raise ValueError(f"radius {radius} too large for height {height}")
    half = cyl / 2.0 + radius

    if spawn_xy is None:
        spawn_xy = _worker_xy(stage)
    # Feet on the ground plane, plus a little clearance to settle under gravity.
    spawn = Gf.Vec3d(float(spawn_xy[0]), float(spawn_xy[1]), half + 0.05)

    # --- /Root/Avatar : identity Xform, the stable handle for S7+ ----------
    UsdGeom.Xform.Define(stage, p["avatar"])

    # --- body_mesh : the capsule PhysX drives ------------------------------
    capsule = UsdGeom.Capsule.Define(stage, p["body"])
    capsule.CreateAxisAttr(up_axis)
    capsule.CreateRadiusAttr(radius)
    capsule.CreateHeightAttr(cyl)
    capsule.CreateExtentAttr([(-radius, -radius, -half), (radius, radius, half)])
    capsule.AddTranslateOp().Set(spawn)
    capsule.AddOrientOp().Set(Gf.Quatf(1.0))
    capsule.AddScaleOp().Set(Gf.Vec3f(1.0))

    body_prim = capsule.GetPrim()
    # Purpose stays "default" -- the shipped CCT demo sets "guide" here, and
    # guide is inherited, so it would silently take the character down with it.
    capsule.CreatePurposeAttr(UsdGeom.Tokens.default_)
    # ...but the capsule itself must not RENDER, or you see a plastic pill
    # around the character. This is the one property of the capsule that
    # changed when the body became a human: geometry, pose and the character
    # controller are all untouched. Physics ignores visibility (NVIDIA's own
    # demo hides its capsule too, via purpose), so the collision behaviour that
    # passed the S6 gates is exactly as it was.
    capsule.CreateVisibilityAttr(UsdGeom.Tokens.invisible)

    # --- physics: character controller, NOT a rigid body -------------------
    # See the module docstring. activate() re-applies this at play time and
    # overwrites upAxis and stepOffset; it is authored here anyway so the saved
    # stage declares the intent and verify_avatar.py can read it statically.
    cct = PhysxSchema.PhysxCharacterControllerAPI.Apply(body_prim)
    cct.CreateUpAxisAttr(up_axis)
    cct.CreateSlopeLimitAttr(0.5)
    cct.CreateStepOffsetAttr(0.2)
    cct.CreateContactOffsetAttr(0.02)

    # --- semantics ---------------------------------------------------------
    # 6.x schema: UsdSemantics.LabelsAPI -> semantics:labels:class. Note the
    # warehouse around it is labelled with the OLD SemanticsAPI schema; see the
    # note in this task's report. Passing the Prim (not a path) keeps this
    # independent of which stage is "current".
    add_labels(body_prim, labels=str(cfg["semantic_class"]), taxonomy="class")

    # --- material: visible colour AND the honest non-visual base -----------
    # Both live on ONE material prim. NonVisualMaterial's own docs: "Non-visual
    # materials can be applied to visual materials ... the visual material must
    # be defined before the non-visual material." So the order here matters.
    # "skin" is base index 34 in
    # exts/isaacsim.core.experimental.materials/data/specifications/base.csv,
    # described there as "Human, pig, etc." -- read, not recalled.
    UsdGeom.Scope.Define(stage, p["looks"])
    visual = PreviewSurfaceMaterial(p["material"])
    visual.set_input_values("diffuseColor", [0.95, 0.42, 0.10])
    visual.set_input_values("roughness", [0.6])
    NonVisualMaterial(p["material"], bases="skin", coatings="none", attributes="none")
    material = UsdShade.Material(stage.GetPrimAtPath(p["material"]))
    UsdShade.MaterialBindingAPI.Apply(body_prim).Bind(material)

    # --- cameras -----------------------------------------------------------
    # A USD camera looks down its own -Z with +Y up. rotateXYZ = (90-pitch, 0,
    # -90) turns that into "looks along world +X, world +Z up, pitched down by
    # `pitch`". +X is forward because that is the axis the character
    # controller's W key drives (omni.physxcct utils.update_movement builds
    # Gf.Vec3f(forward, right, 0) in world space and never rotates it).
    eye = float(cfg["eye_height"]) - (half + 0.05)  # local, relative to capsule centre
    # Sit the eye on the capsule's widest radius: outside the shell, so the
    # body never fills the first-person view, but never ahead of the surface
    # that stops at a wall either. Both offsets are along _FORWARD_X, so the
    # first-person camera leads and the third-person camera trails -- get the
    # sign wrong and the third-person view watches the avatar walk away from
    # you while the first-person view faces the way you came.
    _camera(stage, p["cam_fp"], Gf.Vec3d(radius * _FORWARD_X, 0.0, eye), pitch=0.0, focal=18.0)
    _camera(stage, p["cam_tp"], Gf.Vec3d(-3.0 * _FORWARD_X, 0.0, 1.6), pitch=25.0, focal=24.0)

    # --- the visible body --------------------------------------------------
    if worker_asset:
        _add_character(stage, p, worker_asset, spawn=spawn, half=half, label=str(cfg["semantic_class"]))
    else:
        print("  ! no character asset given -- the avatar has no visible body", flush=True)

    # --- controls ----------------------------------------------------------
    _build_controls_graph(p["graph"], p["body"], speed=cfg["move_speed"])

    return p


# Which way "forward" -- the direction W actually drives the avatar -- points in
# world space. MEASURED, and it is not what the control code reads like:
# `update_movement` builds Gf.Vec3f(forward, right, 0) and hands it to
# set_move(), so W looks like +X. It is not. On an empty stage, commanding +X
# for 60 frames moves the capsule -1.2000 m in X, while commanding +Y moves it
# +1.2000 m in Y -- the X axis is inverted inside the controller and Y is not.
# Both API routes agree exactly (set_move and an authored moveTarget produce the
# same -1.2000), so this is the controller's convention, not one code path's
# quirk. See sim/spikes/cct_movetarget.py.
#
# Everything directional hangs off this one constant, so if the avatar ever
# moonwalks, flip it and rebuild -- nothing else needs touching.
_FORWARD_X = -1.0

# Yaw that turns the asset to face along _FORWARD_X. Derived from the rig, not
# guessed: in the Worker's own frame the ankle joint sits at y=+5.46 cm and the
# toe joint at y=-8.92 cm, so the toes lead towards -Y and the character faces
# -Y. Rotating -90 deg about Z sends -Y to -X; +90 would send it to +X.
_CHARACTER_YAW_DEG = 90.0 * _FORWARD_X

# A human is between these, in metres. Used to decide whether Kit's metrics
# assembler already resolved the asset's centimetre units for us -- see
# _add_character. Wide on purpose: this is a units check, not a height check.
_HUMAN_MIN_M, _HUMAN_MAX_M = 1.2, 2.6


def _add_character(
    stage: Usd.Stage,
    p: dict[str, str],
    asset: str,
    *,
    spawn: Gf.Vec3d,
    half: float,
    label: str,
) -> None:
    """Reference the warehouse's own rigged Worker as the avatar's visible body.

    Reused rather than authored (hard rule 4): this is the same asset, read off
    the stage, that ``/Root/Worker`` already payloads. Its ``SkelAnimation``
    comes along -- it cannot be separated from the asset -- and that is the
    better outcome, not a compromise: with the animation switched off the
    skeleton falls back to its bind pose, which is a **T-pose** (measured:
    hand-to-hand 138.9 cm, hands at shoulder height). The clip is also
    effectively in place -- the root joint moves 1.0 x 1.3 x 0.0 cm across all
    582 frames, i.e. sway, not locomotion -- so it cannot walk the mesh off the
    capsule.

    Structure, and why it is not simply a child of the capsule::

        character   Xform   <- OmniGraph copies the capsule's translate here
          rig       Xform   <- constant feet offset, yaw, unit scale
            (referenced Worker)

    USD ``visibility`` is *pruning*: an invisible prim hides every descendant,
    and ``purpose`` inherits the same way. So the capsule cannot both host the
    character and be hidden. The character is therefore a sibling that follows
    the capsule through the graph, one frame behind -- 1.7 cm at 1 m/s, which
    is not visible, and irrelevant to the sensors since the capsule does not
    render at all.
    """
    # Followed by the graph. Its translate is overwritten every tick, so the
    # value authored here only matters before the first Play.
    char = UsdGeom.Xform.Define(stage, p["character"])
    char.AddTranslateOp().Set(spawn)

    rig = UsdGeom.Xform.Define(stage, p["rig"])
    rig.GetPrim().GetReferences().AddReference(asset)
    # Author the full op order explicitly. Kit's metrics assembler inserts its
    # own `xformOp:scale:unitsResolve` when a referenced asset's metersPerUnit
    # differs from the stage's, and silently doubling up with it would make the
    # character 100x too small. Owning the order makes the outcome ours.
    t_op = rig.AddTranslateOp()
    r_op = rig.AddRotateXYZOp()
    s_op = rig.AddScaleOp()
    t_op.Set(Gf.Vec3d(0.0, 0.0, -half))  # capsule centre -> the soles of the feet
    r_op.Set(Gf.Vec3f(0.0, 0.0, _CHARACTER_YAW_DEG))
    s_op.Set(Gf.Vec3f(1.0, 1.0, 1.0))

    stage.Load(Sdf.Path(p["rig"]))

    # Measure rather than assume which units survived composition.
    bbox = UsdGeom.BBoxCache(Usd.TimeCode.Default(), [UsdGeom.Tokens.default_])
    height = bbox.ComputeWorldBound(rig.GetPrim()).ComputeAlignedRange().GetSize()[2]
    if _HUMAN_MIN_M <= height <= _HUMAN_MAX_M:
        print(f"  character height {height:.3f} m -- units already resolved, scale 1.0", flush=True)
    elif _HUMAN_MIN_M * 100 <= height <= _HUMAN_MAX_M * 100:
        s_op.Set(Gf.Vec3f(0.01, 0.01, 0.01))
        print(f"  character height {height:.1f} cm -- applying 0.01 unit scale", flush=True)
    else:
        raise RuntimeError(
            f"referenced character measures {height} on the up axis, which is neither "
            f"metres nor centimetres for a human. Refusing to guess a scale."
        )

    meshes = [x for x in Usd.PrimRange(rig.GetPrim()) if x.IsA(UsdGeom.Mesh)]
    # Fresh cache, not the one above: BBoxCache memoises, so reusing it here
    # would re-print the pre-scale number and read as though nothing happened.
    final = (
        UsdGeom.BBoxCache(Usd.TimeCode.Default(), [UsdGeom.Tokens.default_])
        .ComputeWorldBound(rig.GetPrim())
        .ComputeAlignedRange()
    )
    print(
        f"  character: {len(meshes)} meshes, world height {final.GetSize()[2]:.3f} m, "
        f"feet at z={final.GetMin()[2]:.3f} m",
        flush=True,
    )

    # Semantics on the geometry that actually renders. The label on the capsule
    # stays too, but the capsule no longer renders, and segmentation labels what
    # is rendered. Labelled on every mesh as well as the root because whether
    # the 6.x annotators resolve INHERITED labels is not something to find out
    # by getting an empty segmentation buffer in S10.
    add_labels(char.GetPrim(), labels=label, taxonomy="class")
    for m in meshes:
        add_labels(m, labels=label, taxonomy="class")

    UsdGeom.Imageable(char).CreatePurposeAttr(UsdGeom.Tokens.default_)
    UsdGeom.Imageable(char).CreateVisibilityAttr(UsdGeom.Tokens.inherited)


def install_character_follow(
    stage: Usd.Stage, avatar_path: str = f"{ROOT}/Avatar"
):
    """Make the visible character track the collision capsule, every frame.

    Python rather than OmniGraph, because OmniGraph cannot see the capsule
    move. The character controller writes its pose to USD; Fabric is never
    updated; ReadPrimAttribute reads Fabric and therefore returns the value it
    cached at setup, forever. Measured: 130 computes, 130 identical values,
    while the capsule travelled 2.58 m. See sim/spikes/_diag_follow_graph.py.

    This is the shipped shape for the problem -- omni.physxcct's own
    first-person camera follows this same capsule with a per-frame callback
    reading UsdGeom.XformCache.

    Returns the subscription. KEEP A REFERENCE: dropping it unsubscribes and
    the character silently stops following.
    """
    import omni.kit.app

    body = stage.GetPrimAtPath(f"{avatar_path}/body_mesh")
    char = stage.GetPrimAtPath(f"{avatar_path}/character")
    if not body.IsValid() or not char.IsValid():
        print(f"  ! cannot install follow: {body.IsValid()=} {char.IsValid()=}", flush=True)
        return None

    attr = char.GetAttribute("xformOp:translate")
    if not attr:
        attr = UsdGeom.Xform(char).AddTranslateOp().GetAttr()
    cache = UsdGeom.XformCache()

    def _follow(_e) -> None:
        # Clear() every frame or the cache returns the pose it saw first --
        # the same staleness, one layer down.
        cache.Clear()
        t = cache.GetLocalToWorldTransform(body).ExtractTranslation()
        attr.Set(Gf.Vec3d(float(t[0]), float(t[1]), float(t[2])))

    sub = omni.kit.app.get_app().get_update_event_stream().create_subscription_to_pop(
        _follow, name="avatar_character_follow"
    )
    print(f"  character follow installed: {body.GetPath()} -> {char.GetPath()}", flush=True)
    return sub


def _camera(stage: Usd.Stage, path: str, translate: Gf.Vec3d, *, pitch: float, focal: float) -> None:
    cam = UsdGeom.Camera.Define(stage, path)
    cam.AddTranslateOp().Set(translate)
    # A USD camera looks down its own -Z with +Y up. rotateXYZ = (90-pitch, 0,
    # -90*_FORWARD_X) turns that into "looks along the direction of travel,
    # world +Z up, pitched down by `pitch`".
    cam.AddRotateXYZOp().Set(Gf.Vec3f(90.0 - pitch, 0.0, -90.0 * _FORWARD_X))
    cam.CreateFocalLengthAttr(focal)
    # USD's default near plane is 1.0. In a warehouse that hides everything
    # within a metre of your face, which reads as "the camera is broken".
    cam.CreateClippingRangeAttr(Gf.Vec2f(0.01, 1_000_000.0))


def _worker_xy(stage: Usd.Stage) -> tuple[float, float]:
    """Where the warehouse's own Worker character stands, from a live stage.

    A human-shaped prop is already standing somewhere valid; borrowing its
    ground position is strictly better than inventing coordinates that might be
    inside a shelf. Falls back to the origin if the Worker is ever removed.
    """
    worker = stage.GetPrimAtPath(f"{ROOT}/Worker")
    if not worker.IsValid():
        print(f"  ! {ROOT}/Worker not found -- spawning at the origin instead", flush=True)
        return (0.0, 0.0)
    m = UsdGeom.XformCache().GetLocalToWorldTransform(worker)
    t = m.ExtractTranslation()
    return (float(t[0]), float(t[1]))


def read_base_facts(base: Path) -> dict:
    """Everything the build needs from the base stage, read from the LAYER.

    Deliberately Sdf-only: opening a *layer* reads a file, opening a *stage*
    composes 26,000 prims and 3,469 exact-triangle-mesh colliders, and the
    moment a physics extension is enabled against that, PhysX cooks every one
    of them. That cooking pass ran for over 13 minutes at 880% CPU and did not
    finish -- and the avatar layer does not need a single warehouse prim to be
    authored. So this reads the four facts it actually needs and never composes
    the warehouse at all.

    All four are authored in the base layer itself, not inside a payload --
    verified before relying on it.
    """
    layer = Sdf.Layer.FindOrOpen(str(base))
    if layer is None:
        raise RuntimeError(f"could not open base layer: {base}")

    # Layer metadata lives as info fields on the layer's pseudo-root prim spec.
    root = layer.pseudoRoot
    facts: dict = {
        "default_prim": layer.defaultPrim,
        "up_axis": root.GetInfo("upAxis") if root.HasInfo("upAxis") else None,
        "meters_per_unit": root.GetInfo("metersPerUnit") if root.HasInfo("metersPerUnit") else None,
        "worker_xy": None,
        "worker_asset": None,
        "gravity": None,
    }

    # Both are authored in the base's root layer (checked). If that ever stops
    # being true, fail loudly here rather than silently defaulting to USD's
    # Y-up / centimetres, which would put the avatar on its side at 1/100 scale.
    if facts["up_axis"] is None or facts["meters_per_unit"] is None:
        raise RuntimeError(
            f"{base.name} does not author upAxis/metersPerUnit in its root layer "
            f"(got {facts['up_axis']!r}/{facts['meters_per_unit']!r}); refusing to guess"
        )

    worker = layer.GetPrimAtPath(f"{ROOT}/Worker")
    if worker is not None and "xformOp:transform" in worker.properties:
        default = worker.properties["xformOp:transform"].default
        if default is not None:
            t = default.ExtractTranslation()
            facts["worker_xy"] = (float(t[0]), float(t[1]))
    # The character asset the avatar borrows its body from. Read from the arc
    # the stage already declares -- never typed out from memory (hard rule 1
    # is about prim paths, but an asset URL recalled wrongly fails the same
    # way: it resolves to nothing and the avatar is simply not there).
    if worker is not None:
        items = list(worker.payloadList.prependedItems) + list(worker.payloadList.appendedItems)
        refs = list(worker.referenceList.prependedItems) + list(worker.referenceList.appendedItems)
        for item in items + refs:
            if item.assetPath:
                facts["worker_asset"] = item.assetPath
                break

    scene = layer.GetPrimAtPath("/PhysicsScene")
    if scene is not None:
        facts["gravity"] = {
            k: (scene.properties[k].default if k in scene.properties else "<schema fallback>")
            for k in ("physics:gravityDirection", "physics:gravityMagnitude")
        }
    return facts


def _build_controls_graph(graph_path: str, body_path: str, *, speed: float) -> None:
    """Wire the shipped character-controller node to the avatar's capsule.

    The whole graph is three nodes because ``setupControls="Auto"`` makes the
    node bind WASD/E/Q and gamepad itself -- that is the "reuse existing
    wiring" the task asks for, and it lives in the USD, so the GUI session
    needs no script running: open the stage, press Play, walk.
    """
    # Not enabled by ANY shipped .kit experience -- checked across
    # /isaac-sim/apps/*.kit. Without it the node type is unregistered, and an
    # unregistered node type in a saved graph is a silent no-op.
    enable_extension("omni.physx.cct")

    # inputs:speed is typed `int` (units/s) in OgnCharacterController.ogn, and
    # this stage is 1.0 m/unit, so the finest control available is whole m/s.
    speed_i = max(1, int(round(float(speed))))
    if abs(speed_i - float(speed)) > 1e-6:
        print(
            f"  ! move_speed {speed} m/s -> {speed_i} m/s: the character "
            "controller node types speed as an int and the stage is in metres",
            flush=True,
        )

    # The character's follow is NOT in this graph, and that is a measured
    # decision rather than a preference. It used to be
    # OnTick -> ReadPrimAttribute -> WritePrimAttribute, correctly wired, and it
    # copied a constant: the character controller writes the capsule's pose to
    # USD, Fabric never receives it, and OmniGraph's ReadPrimAttribute reads
    # Fabric. Instrumented over 120 frames while the capsule travelled 2.58 m:
    # follow_tick computed 176 times, read_body 130 times, write_character 130
    # times, and read_body's outputs:value was byte-identical at every single
    # one. A graph that ticks, reads and writes, and does nothing.
    #
    # install_character_follow() does it in Python instead, which is also what
    # omni.physxcct's own first-person camera does to follow the same capsule --
    # a per-frame callback reading UsdGeom.XformCache. Shipped pattern, not a
    # local invention.
    keys = og.Controller.Keys
    og.Controller.edit(
        {"graph_path": graph_path, "evaluator_name": "execution"},
        {
            keys.CREATE_NODES: [
                ("on_play", "omni.graph.action.OnStageEvent"),
                ("on_stop", "omni.graph.action.OnStageEvent"),
                ("cct", "omni.physx.cct.OgnCharacterController"),
            ],
            keys.SET_VALUES: [
                ("on_play.inputs:eventName", "Simulation Start Play"),
                ("on_play.inputs:onlyPlayback", True),
                ("on_stop.inputs:eventName", "Simulation Stop Play"),
                ("on_stop.inputs:onlyPlayback", True),
                ("cct.inputs:capsulePath", body_path),
                ("cct.inputs:gravity", True),
                ("cct.inputs:speed", speed_i),
                ("cct.inputs:setupControls", "Auto"),
                # fpCameraPathToken deliberately unset: that mode hijacks the
                # active viewport and recentres the OS cursor every frame,
                # which is wrong over a livestream. The cameras are parented
                # instead, so switching view is rebinding the viewport.
            ],
            keys.CONNECT: [
                ("on_play.outputs:execOut", "cct.inputs:activate"),
                ("on_stop.outputs:execOut", "cct.inputs:deactivate"),
            ],
        },
    )


# ---------------------------------------------------------------------------
# Script entry point
# ---------------------------------------------------------------------------
def _attach_base_sublayer(out: Path, base: Path, facts: dict) -> None:
    """Turn the exported avatar-only layer into a layer that sublayers the base.

    Done with Sdf, on a layer, *after* everything is authored. Opening a layer
    reads a file; it does not compose a stage, so the warehouse is never built
    in this process and PhysX never sees a collider. Stage metadata does not
    compose across sublayers -- defaultPrim, upAxis and metersPerUnit are read
    from the root layer only -- so they are re-authored here from the base's
    own values.
    """
    layer = Sdf.Layer.FindOrOpen(str(out))
    if layer is None:
        raise RuntimeError(f"exported layer vanished: {out}")
    # Relative, so the pair of files stays portable between host and container.
    layer.subLayerPaths = [f"./{base.name}"]
    layer.defaultPrim = facts["default_prim"]
    layer.pseudoRoot.SetInfo("upAxis", facts["up_axis"])
    layer.pseudoRoot.SetInfo("metersPerUnit", facts["meters_per_unit"])
    layer.Save()


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path, default=OUT_STAGE)
    ap.add_argument("--base", type=Path, default=BASE_STAGE)
    ap.add_argument(
        "--spawn",
        default=None,
        help="ground position 'x,y'. Default: wherever the Worker stands.",
    )
    args = ap.parse_args(argv)

    if not args.base.exists():
        print(f"FAIL: base stage not found: {args.base}", flush=True)
        return 1

    print(f"base stage : {args.base}", flush=True)
    print(f"output     : {args.out}", flush=True)

    facts = read_base_facts(args.base)
    print(
        f"base facts : defaultPrim=/{facts['default_prim']} up={facts['up_axis']} "
        f"m/unit={facts['meters_per_unit']}",
        flush=True,
    )
    # Gravity in the wrong units makes the avatar fall at 100x, which reads as a
    # physics bug. Cheap to print, expensive to discover later.
    print(f"physics    : /PhysicsScene {facts['gravity']}", flush=True)

    if args.spawn:
        x, y = (float(v) for v in args.spawn.split(","))
        spawn_xy = (x, y)
    else:
        spawn_xy = facts["worker_xy"]
        if spawn_xy is None:
            print("  ! no Worker transform in the base layer -- spawning at origin", flush=True)
            spawn_xy = (0.0, 0.0)
    print(f"spawn      : {spawn_xy}", flush=True)
    print(f"character  : {facts['worker_asset']}", flush=True)
    if not facts["worker_asset"]:
        print("  ! /Root/Worker declares no asset -- avatar will have no visible body", flush=True)

    # An EMPTY stage, deliberately. See read_base_facts(): composing the
    # warehouse here and then enabling a physics extension puts PhysX into a
    # multi-minute cook of 3,469 triangle meshes for no benefit -- the avatar
    # layer references nothing in the warehouse. The base is attached as a
    # sublayer afterwards, at the Sdf level, where no composition happens.
    ctx = omni.usd.get_context()
    ctx.new_stage()
    for _ in range(10):
        _APP.update()
    stage = ctx.get_stage()
    if stage is None:
        print("FAIL: could not create a stage", flush=True)
        return 1

    UsdGeom.SetStageUpAxis(stage, facts["up_axis"])
    UsdGeom.SetStageMetersPerUnit(stage, facts["meters_per_unit"])
    # A "new stage" is not always empty -- whatever template Kit used would end
    # up authored into the avatar layer and composed over the warehouse.
    for prim in list(stage.GetPseudoRoot().GetChildren()):
        if prim.GetPath().pathString != ROOT:
            print(f"  dropping template prim {prim.GetPath()}", flush=True)
            stage.RemovePrim(prim.GetPath())
    UsdGeom.Xform.Define(stage, ROOT)

    paths = add_avatar(stage, spawn_xy=spawn_xy, worker_asset=facts["worker_asset"])

    for _ in range(5):
        _APP.update()

    if args.out.exists():
        args.out.unlink()
    stage.GetRootLayer().Export(str(args.out))
    _attach_base_sublayer(args.out, args.base, facts)

    print("\nbuilt:", flush=True)
    for k, v in paths.items():
        print(f"  {k:9s} {v}", flush=True)
    print(f"\nsaved {args.out} ({args.out.stat().st_size} bytes)", flush=True)
    print("Open THAT stage in the GUI, not observatory_base.usd.", flush=True)
    return 0


if __name__ == "__main__":
    code = main()
    # Do NOT hand the exit code to Kit's teardown. SimulationApp.close() races
    # with its own task group on this host and aborts with
    #   "Destroying busy TaskGroup!"  ->  Fatal Python error: Aborted
    # *after* the stage is authored, saved and closed -- turning a completely
    # successful build into exit 1. It is a SIGABRT, so it cannot be caught.
    # Everything this script produces is already on disk by now, so leave on
    # our own terms. A real failure still surfaces: an exception in main()
    # propagates and never reaches this line.
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(code)
