"""The avatar: the one moving entity in the observatory. Layer 1 (scene/USD).

Structure built (all paths under the REAL stage root ``/Root`` -- there is no
``/World`` on this stage; confirmed in the GUI 2026-08-15)::

    /Root/Avatar                    Xform, identity, never moves
      +-- Looks/avatar_skin         UsdPreviewSurface + non-visual "skin"
      +-- body_mesh                 Capsule -- collision. PhysX moves this one.
      |     |                       INVISIBLE: it collides, it does not render.
      |     +-- cam_first_person    eye height, looks along travel
      |     +-- cam_third_person    3 m behind, 1.6 m up, pitched down 25 deg
      +-- character                 what you SEE: the warehouse's rigged Worker,
      |     +-- rig                 referenced. Follows body_mesh via the graph.
      +-- Controls                  OmniGraph: character controller + the follow

Why the cameras hang off ``body_mesh`` and not off ``/Root/Avatar``
-------------------------------------------------------------------
Physics moves the *capsule*, not its parent. Cameras parented to the Xform
would stay behind while the body walked away -- a silent failure of exactly the
kind this project keeps a list of. They are still descendants of the Avatar
Xform, switching view is still just rebinding the viewport, and nothing ever
drives a camera directly. ``/Root/Avatar`` is deliberately left at identity:
the character controller writes a *world* pose back onto the capsule, so a
non-identity parent would teleport the avatar on the first simulated frame.

Why a PhysX character controller and not a kinematic rigid body
----------------------------------------------------------------
The gate for this task is "walking into a shelf stops you". A kinematic rigid
body **cannot** do that: PhysX moves a kinematic actor to its target pose
unconditionally and does not depenetrate it, so it drives straight through
static geometry. Kinematic-vs-static contacts are not even generated by
default. The requirement "kinematic, not dynamic" and the requirement "the
shelf stops you" are not jointly satisfiable by a rigid body.

``PhysxCharacterControllerAPI`` is the resolution and is what the requirement
was reaching for. PhysX implements a CCT *as* a kinematic actor -- the schema's
own doc for ``scaleCoeff`` says "scale coefficient for underlying kinematic
actor" -- so nothing here ragdolls, trips, or falls through a floor. On top of
that it does collide-and-slide against static geometry, which is the half a
kinematic body cannot do.

Two consequences, both deliberate:

  * The capsule carries **no** ``UsdPhysics.CollisionAPI``. A prim with
    CollisionAPI and no rigid body is *static* collision geometry, so applying
    it here would park a static capsule inside the character controller's own
    actor and fight it. The CCT is the collision representation.
  * What ray-based sensors bounce off is **render** geometry, not colliders --
    RTX lidar and radar trace the same BVH the renderer does. So the avatar
    needs a visible mesh for its own sake, and that is ``character``, not the
    capsule. The capsule is hidden with ``visibility = "invisible"`` and keeps
    ``purpose = "default"``; NVIDIA's own CCT demo hides its capsule with
    ``purpose = "guide"`` instead, which is inherited and would take the
    character down with it. ``verify_avatar.py`` asserts both halves: the
    capsule does not render, and the character does.

Execution model
---------------
This script creates prims and saves USD. It reads no sensor data, so exec mode
(see CLAUDE.md) does not apply and ``SimulationApp`` is correct. It does need
Kit running, for the asset resolver and for the OmniGraph node registry.

Reused rather than written (hard rule 4)
----------------------------------------
The control wiring is NVIDIA's, from two shipped examples:

  * ``isaacsim.examples.interactive.omnigraph_keyboard`` -- Isaac Examples ->
    Input Devices -> Omnigraph Keyboard. Read first, as instructed. What it
    actually does: builds an ``omni.graph.action`` execution graph in which
    ``OnTick`` (``onlyPlayback=True``) drives ``ReadKeyboardState`` nodes for
    'A' and 'D', converts their booleans to doubles, negates one, scales the
    sum by 0.1, and read-modify-writes a prim attribute through
    ``ReadPrimAttribute`` -> ``Add`` -> ``WritePrimAttribute``. It resizes a
    cube. The transferable part is the accumulator pattern, not the graph.
  * ``omni.physx.cct`` -> Physics demos -> Character Controller -> "Action
    Graph" (``data/demos/actiongraph.usd``). Same idea, finished: an
    ``OnStageEvent('Simulation Start Play')`` activates an
    ``omni.physx.cct.OgnCharacterController`` node, whose ``setupControls =
    "Auto"`` binds WASD/E/Q and gamepad for us. That is the wiring below, with
    the demo's arrow-key rebinding and its ``purpose="guide"`` capsule dropped,
    and its centimetre-stage numbers converted to metres.

Controls, once you press Play (defaults from
``omni.physxcct.scripts.utils.setup_controls``)::

    W / S   forward / back   (world -X / +X -- MEASURED, not read off the
    A / D   left / right      control code, which looks like it means +X. The
    E / Q   jump / down       controller inverts X and not Y; see _FORWARD_X.
                              Movement is world-axis: it does not follow the
                              view, because the view cannot be turned.)

The second entry point: :func:`set_avatar_pose`
------------------------------------------------
Episode reset needs to place the avatar from code, repeatedly, without
restarting the simulator, and every benchmark this project is aimed at
(HM3D, MP3D, GOAT-Bench, HM3D-OVON, A-EQA) begins each episode by doing
exactly that. :func:`set_avatar_pose` is that call. It is an **addition**, not
a replacement: it touches neither the Controls graph nor the controller's
registration, so the keyboard keeps working and simply carries on from
wherever the pose was written.

It is a pose WRITE, which is not the same thing as a walk. See that function's
docstring for which route it takes through -- or around -- the character
controller, and for what "not collide-and-slide" costs.
``sim/verify_avatar_pose.py`` is the headless check that it lands and that a
fixed sensor sees it land.

Run::

    docker compose -f docker/docker-compose.yml run --rm sim \\
        ./python.sh /workspace/sim/avatar.py
"""

from __future__ import annotations

# --- SimulationApp must exist before any omni/pxr/isaacsim import (hard rule 3)
# When this file is imported (S7 wants that), Kit is already up and this block
# is skipped. When it is run as a script, this is the first thing that happens.
if __name__ == "__main__":
    from isaacsim import SimulationApp

    _APP = SimulationApp({"headless": True})
else:
    _APP = None

import argparse  # noqa: E402
import math  # noqa: E402
import os  # noqa: E402
import sys  # noqa: E402
from pathlib import Path  # noqa: E402

import omni.graph.core as og  # noqa: E402
import omni.usd  # noqa: E402
import yaml  # noqa: E402
from isaacsim.core.experimental.materials import (  # noqa: E402
    NonVisualMaterial,
    PreviewSurfaceMaterial,
)
from isaacsim.core.experimental.utils.app import enable_extension  # noqa: E402
from isaacsim.core.experimental.utils.semantics import add_labels  # noqa: E402
from pxr import Gf, PhysxSchema, Sdf, Usd, UsdGeom, UsdShade, Vt  # noqa: E402

REPO = Path(__file__).resolve().parent.parent
SCENE_YAML = REPO / "config" / "scene.yaml"
BASE_STAGE = REPO / "sim" / "observatory_base.usd"

# The stage this script writes. NOT observatory_base.usd: that file is the
# tracked S5 artifact (6.5 MB, committed at 470ea5d) and the base every later
# task starts from. Overwriting it would make this script destructive and
# non-idempotent, and would put a 6.5 MB binary diff in every avatar tweak.
# The output is a thin layer that SUBLAYERS the base, so it costs a few KB and
# the base stays authoritative. scenes/ is not an option: it is a symlink to
# /ssd1/quang/scenes, which is not mounted into the container.
OUT_STAGE = REPO / "sim" / "observatory_avatar.usd"

# Stage root. Read off the real stage, never invented (hard rule 1).
ROOT = "/Root"


def _paths(avatar_path: str) -> dict[str, str]:
    """Every prim path this module touches, derived from one root."""
    return {
        "avatar": avatar_path,
        "body": f"{avatar_path}/body_mesh",
        "character": f"{avatar_path}/character",
        "rig": f"{avatar_path}/character/rig",
        "cam_fp": f"{avatar_path}/body_mesh/cam_first_person",
        "cam_tp": f"{avatar_path}/body_mesh/cam_third_person",
        "looks": f"{avatar_path}/Looks",
        "material": f"{avatar_path}/Looks/avatar_skin",
        "graph": f"{avatar_path}/Controls",
    }


def load_avatar_config(path: Path = SCENE_YAML) -> dict:
    """The avatar block of config/scene.yaml. The config is the contract."""
    with open(path, encoding="utf-8") as fh:
        return yaml.safe_load(fh)["avatar"]


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
def add_avatar(
    stage: Usd.Stage | None = None,
    *,
    config: dict | None = None,
    spawn_xy: tuple[float, float] | None = None,
    worker_asset: str | None = None,
) -> dict[str, str]:
    """Add the avatar to an already-open stage and return its prim paths.

    Structured this way because S7 needs to drop an avatar into a stage that is
    already open in the GUI, not only into one this script opened.

    Args:
        stage: Target stage. Defaults to the current Kit stage, which is what
            both callers actually have. A stage that is not the current one is
            rejected loudly rather than half-built: the Isaac material and
            semantics helpers resolve against the current stage.
        config: The ``avatar`` block of config/scene.yaml. Read from disk if
            not given.
        worker_asset: USD asset the visible body is referenced from -- the same
            rigged character ``/Root/Worker`` payloads, read off the stage by
            :func:`read_base_facts` rather than written out here. Without it the
            avatar is a bare (invisible) collision capsule.
        spawn_xy: Ground position. Defaults to wherever the warehouse's own
            Worker character is standing -- a spot a human-sized capsule is
            known to fit, read from the stage instead of guessed. A guessed
            coordinate that lands inside a shelf leaves the controller stuck
            with no error.

    Returns:
        The prim paths created, keyed by role.
    """
    ctx = omni.usd.get_context()
    current = ctx.get_stage()
    if stage is None:
        stage = current
    if stage is None:
        raise RuntimeError("no stage is open -- open one before calling add_avatar()")
    if stage != current:
        raise ValueError(
            "add_avatar() only builds into the CURRENT Kit stage; the Isaac "
            "material and semantics helpers resolve against it. Open the "
            "target stage in the usd context first."
        )

    cfg = config or load_avatar_config()
    p = _paths(cfg["prim_path"])

    up_axis = UsdGeom.GetStageUpAxis(stage)
    if up_axis != UsdGeom.Tokens.z:
        raise RuntimeError(
            f"stage up axis is {up_axis!r}; the character controller's movement "
            "code treats index 2 as vertical, so this avatar assumes Z-up"
        )
    if not stage.GetPrimAtPath(ROOT).IsValid():
        raise RuntimeError(f"{ROOT} not found on the stage -- wrong stage?")

    # --- geometry ---------------------------------------------------------
    # height = cylinder + two hemispherical caps, so the cylinder is
    # height - 2*radius and the centre sits half a height off the floor.
    height = float(cfg["height"])
    radius = float(cfg.get("radius", 0.30))
    cyl = height - 2.0 * radius
    if cyl <= 0:
        raise ValueError(f"radius {radius} too large for height {height}")
    half = cyl / 2.0 + radius

    if spawn_xy is None:
        spawn_xy = _worker_xy(stage)
    # Feet on the ground plane, plus a little clearance to settle under gravity.
    spawn = Gf.Vec3d(float(spawn_xy[0]), float(spawn_xy[1]), half + 0.05)

    # --- /Root/Avatar : identity Xform, the stable handle for S7+ ----------
    UsdGeom.Xform.Define(stage, p["avatar"])

    # --- body_mesh : the capsule PhysX drives ------------------------------
    capsule = UsdGeom.Capsule.Define(stage, p["body"])
    capsule.CreateAxisAttr(up_axis)
    capsule.CreateRadiusAttr(radius)
    capsule.CreateHeightAttr(cyl)
    capsule.CreateExtentAttr([(-radius, -radius, -half), (radius, radius, half)])
    capsule.AddTranslateOp().Set(spawn)
    capsule.AddOrientOp().Set(Gf.Quatf(1.0))
    capsule.AddScaleOp().Set(Gf.Vec3f(1.0))

    body_prim = capsule.GetPrim()
    # Purpose stays "default" -- the shipped CCT demo sets "guide" here, and
    # guide is inherited, so it would silently take the character down with it.
    capsule.CreatePurposeAttr(UsdGeom.Tokens.default_)
    # ...but the capsule itself must not RENDER, or you see a plastic pill
    # around the character. This is the one property of the capsule that
    # changed when the body became a human: geometry, pose and the character
    # controller are all untouched. Physics ignores visibility (NVIDIA's own
    # demo hides its capsule too, via purpose), so the collision behaviour that
    # passed the S6 gates is exactly as it was.
    capsule.CreateVisibilityAttr(UsdGeom.Tokens.invisible)

    # --- physics: character controller, NOT a rigid body -------------------
    # See the module docstring. activate() re-applies this at play time and
    # overwrites upAxis and stepOffset; it is authored here anyway so the saved
    # stage declares the intent and verify_avatar.py can read it statically.
    cct = PhysxSchema.PhysxCharacterControllerAPI.Apply(body_prim)
    cct.CreateUpAxisAttr(up_axis)
    apply_controller_tuning(body_prim, cfg.get("controller"))

    # --- semantics ---------------------------------------------------------
    # 6.x schema: UsdSemantics.LabelsAPI -> semantics:labels:class. Note the
    # warehouse around it is labelled with the OLD SemanticsAPI schema; see the
    # note in this task's report. Passing the Prim (not a path) keeps this
    # independent of which stage is "current".
    add_labels(body_prim, labels=str(cfg["semantic_class"]), taxonomy="class")

    # --- material: visible colour AND the honest non-visual base -----------
    # Both live on ONE material prim. NonVisualMaterial's own docs: "Non-visual
    # materials can be applied to visual materials ... the visual material must
    # be defined before the non-visual material." So the order here matters.
    # "skin" is base index 34 in
    # exts/isaacsim.core.experimental.materials/data/specifications/base.csv,
    # described there as "Human, pig, etc." -- read, not recalled.
    UsdGeom.Scope.Define(stage, p["looks"])
    visual = PreviewSurfaceMaterial(p["material"])
    visual.set_input_values("diffuseColor", [0.95, 0.42, 0.10])
    visual.set_input_values("roughness", [0.6])
    NonVisualMaterial(p["material"], bases="skin", coatings="none", attributes="none")
    material = UsdShade.Material(stage.GetPrimAtPath(p["material"]))
    UsdShade.MaterialBindingAPI.Apply(body_prim).Bind(material)

    # --- cameras -----------------------------------------------------------
    # A USD camera looks down its own -Z with +Y up. rotateXYZ = (90-pitch, 0,
    # -90) turns that into "looks along world +X, world +Z up, pitched down by
    # `pitch`". +X is forward because that is the axis the character
    # controller's W key drives (omni.physxcct utils.update_movement builds
    # Gf.Vec3f(forward, right, 0) in world space and never rotates it).
    eye = float(cfg["eye_height"]) - (half + 0.05)  # local, relative to capsule centre
    # Sit the eye on the capsule's widest radius: outside the shell, so the
    # body never fills the first-person view, but never ahead of the surface
    # that stops at a wall either. Both offsets are along _FORWARD_X, so the
    # first-person camera leads and the third-person camera trails -- get the
    # sign wrong and the third-person view watches the avatar walk away from
    # you while the first-person view faces the way you came.
    _camera(stage, p["cam_fp"], Gf.Vec3d(radius * _FORWARD_X, 0.0, eye), pitch=0.0, focal=18.0)
    _camera(stage, p["cam_tp"], Gf.Vec3d(-3.0 * _FORWARD_X, 0.0, 1.6), pitch=25.0, focal=24.0)

    # --- the visible body --------------------------------------------------
    if worker_asset:
        _add_character(stage, p, worker_asset, spawn=spawn, half=half, label=str(cfg["semantic_class"]))
    else:
        print("  ! no character asset given -- the avatar has no visible body", flush=True)

    # --- controls ----------------------------------------------------------
    _build_controls_graph(p["graph"], p["body"], speed=cfg["move_speed"])

    return p


# Which way "forward" -- the direction W actually drives the avatar -- points in
# world space. MEASURED, and it is not what the control code reads like:
# `update_movement` builds Gf.Vec3f(forward, right, 0) and hands it to
# set_move(), so W looks like +X. It is not. On an empty stage, commanding +X
# for 60 frames moves the capsule -1.2000 m in X, while commanding +Y moves it
# +1.2000 m in Y -- the X axis is inverted inside the controller and Y is not.
# Both API routes agree exactly (set_move and an authored moveTarget produce the
# same -1.2000), so this is the controller's convention, not one code path's
# quirk. See sim/spikes/cct_movetarget.py.
#
# Everything directional hangs off this one constant, so if the avatar ever
# moonwalks, flip it and rebuild -- nothing else needs touching.
_FORWARD_X = -1.0

# Yaw that turns the asset to face along _FORWARD_X. Derived from the rig, not
# guessed: in the Worker's own frame the ankle joint sits at y=+5.46 cm and the
# toe joint at y=-8.92 cm, so the toes lead towards -Y and the character faces
# -Y. Rotating -90 deg about Z sends -Y to -X; +90 would send it to +X.
_CHARACTER_YAW_DEG = 90.0 * _FORWARD_X

# Which way the referenced Worker asset faces in ITS OWN frame, expressed the
# way set_avatar_pose() expresses every heading: degrees about +Z, 0 = world
# +X, counter-clockwise positive. The toes lead towards -Y (the ankle/toe
# measurement above), and the heading of -Y is atan2(-1, 0) = -90 deg. Same
# measurement as _CHARACTER_YAW_DEG, stated in the units the pose API uses.
_ASSET_FACING_DEG = -90.0

# The heading the avatar is BUILT facing, and therefore the heading its cameras
# already look along before any yaw is written: the direction W drives, which
# is _FORWARD_X. Both halves of the rig agree on it by construction --
# _ASSET_FACING_DEG + _CHARACTER_YAW_DEG is -180 for _FORWARD_X = -1 and 0 for
# +1 -- and set_avatar_pose() re-derives the character half from the stage and
# complains if that identity has stopped holding.
_DEFAULT_HEADING_DEG = 0.0 if _FORWARD_X > 0 else 180.0

# A USD camera authored the way both _camera() below and
# sensor_factory.look_at_rotate_xyz() author one carries
# ``rotateXYZ = (90 - pitch, 0, heading - 90)``: the camera looks down its own
# -Z, and that composition sends -Z to the horizontal bearing `heading` with a
# downward pitch. So the heading a camera looks along is its rz plus this.
# MEASURED against the built stage rather than derived: cam_first_person holds
# rotateXYZ (90, 0, 90) and its world forward is (-1, 0, 0), i.e. heading 180,
# which is _DEFAULT_HEADING_DEG.
_CAMERA_RZ_TO_HEADING_DEG = 90.0

# A human is between these, in metres. Used to decide whether Kit's metrics
# assembler already resolved the asset's centimetre units for us -- see
# _add_character. Wide on purpose: this is a units check, not a height check.
_HUMAN_MIN_M, _HUMAN_MAX_M = 1.2, 2.6


def _add_character(
    stage: Usd.Stage,
    p: dict[str, str],
    asset: str,
    *,
    spawn: Gf.Vec3d,
    half: float,
    label: str,
) -> None:
    """Reference the warehouse's own rigged Worker as the avatar's visible body.

    Reused rather than authored (hard rule 4): this is the same asset, read off
    the stage, that ``/Root/Worker`` already payloads. Its ``SkelAnimation``
    comes along -- it cannot be separated from the asset -- and that is the
    better outcome, not a compromise: with the animation switched off the
    skeleton falls back to its bind pose, which is a **T-pose** (measured:
    hand-to-hand 138.9 cm, hands at shoulder height). The clip is also
    effectively in place -- the root joint moves 1.0 x 1.3 x 0.0 cm across all
    582 frames, i.e. sway, not locomotion -- so it cannot walk the mesh off the
    capsule.

    Structure, and why it is not simply a child of the capsule::

        character   Xform   <- OmniGraph copies the capsule's translate here
          rig       Xform   <- constant feet offset, yaw, unit scale
            (referenced Worker)

    USD ``visibility`` is *pruning*: an invisible prim hides every descendant,
    and ``purpose`` inherits the same way. So the capsule cannot both host the
    character and be hidden. The character is therefore a sibling that follows
    the capsule through the graph, one frame behind -- 1.7 cm at 1 m/s, which
    is not visible, and irrelevant to the sensors since the capsule does not
    render at all.
    """
    # Followed by the graph. Its translate is overwritten every tick, so the
    # value authored here only matters before the first Play.
    char = UsdGeom.Xform.Define(stage, p["character"])
    char.AddTranslateOp().Set(spawn)

    rig = UsdGeom.Xform.Define(stage, p["rig"])
    rig.GetPrim().GetReferences().AddReference(asset)
    # Author the full op order explicitly. Kit's metrics assembler inserts its
    # own `xformOp:scale:unitsResolve` when a referenced asset's metersPerUnit
    # differs from the stage's, and silently doubling up with it would make the
    # character 100x too small. Owning the order makes the outcome ours.
    t_op = rig.AddTranslateOp()
    r_op = rig.AddRotateXYZOp()
    s_op = rig.AddScaleOp()
    t_op.Set(Gf.Vec3d(0.0, 0.0, -half))  # capsule centre -> the soles of the feet
    r_op.Set(Gf.Vec3f(0.0, 0.0, _CHARACTER_YAW_DEG))
    s_op.Set(Gf.Vec3f(1.0, 1.0, 1.0))

    stage.Load(Sdf.Path(p["rig"]))

    # Measure rather than assume which units survived composition.
    bbox = UsdGeom.BBoxCache(Usd.TimeCode.Default(), [UsdGeom.Tokens.default_])
    height = bbox.ComputeWorldBound(rig.GetPrim()).ComputeAlignedRange().GetSize()[2]
    if _HUMAN_MIN_M <= height <= _HUMAN_MAX_M:
        print(f"  character height {height:.3f} m -- units already resolved, scale 1.0", flush=True)
    elif _HUMAN_MIN_M * 100 <= height <= _HUMAN_MAX_M * 100:
        s_op.Set(Gf.Vec3f(0.01, 0.01, 0.01))
        print(f"  character height {height:.1f} cm -- applying 0.01 unit scale", flush=True)
    else:
        raise RuntimeError(
            f"referenced character measures {height} on the up axis, which is neither "
            f"metres nor centimetres for a human. Refusing to guess a scale."
        )

    meshes = [x for x in Usd.PrimRange(rig.GetPrim()) if x.IsA(UsdGeom.Mesh)]
    # Fresh cache, not the one above: BBoxCache memoises, so reusing it here
    # would re-print the pre-scale number and read as though nothing happened.
    final = (
        UsdGeom.BBoxCache(Usd.TimeCode.Default(), [UsdGeom.Tokens.default_])
        .ComputeWorldBound(rig.GetPrim())
        .ComputeAlignedRange()
    )
    print(
        f"  character: {len(meshes)} meshes, world height {final.GetSize()[2]:.3f} m, "
        f"feet at z={final.GetMin()[2]:.3f} m",
        flush=True,
    )

    # Semantics on the geometry that actually renders. The label on the capsule
    # stays too, but the capsule no longer renders, and segmentation labels what
    # is rendered. Labelled on every mesh as well as the root because whether
    # the 6.x annotators resolve INHERITED labels is not something to find out
    # by getting an empty segmentation buffer in S10.
    add_labels(char.GetPrim(), labels=label, taxonomy="class")
    stripped = 0
    for m in meshes:
        add_labels(m, labels=label, taxonomy="class")
        # Strip the OLD-schema per-part labels the asset carries. The Worker
        # ships SemanticsAPI:Semantics_* on every mesh -- fieldjacket, basebody,
        # baseballcap, cargopant, basketballshoes -- and the annotator resolves
        # ONE class per prim from the two schemas present. The result was the
        # avatar coming back as 2,351 'person' pixels with the rest of the body
        # attributed to its clothing. Removing them leaves a single answer per
        # prim, so the whole silhouette reads as one person.
        #
        # Removed only on the AVATAR's copy: these are overrides under
        # /Root/Avatar/character, so the warehouse's own Worker keeps its
        # per-part labels and S10 still has them to look at.
        for schema in list(m.GetAppliedSchemas()):
            if schema.startswith("SemanticsAPI:"):
                try:
                    m.RemoveAppliedSchema(schema)
                    stripped += 1
                except Exception:
                    inst = schema.split(":", 1)[-1]
                    for suffix in ("semanticType", "semanticData"):
                        a = m.GetAttribute(f"semantic:{inst}:params:{suffix}")
                        if a:
                            a.Set("")
                            stripped += 1
    print(f"  stripped {stripped} inherited per-part semantic schemas from the character",
          flush=True)

    UsdGeom.Imageable(char).CreatePurposeAttr(UsdGeom.Tokens.default_)
    UsdGeom.Imageable(char).CreateVisibilityAttr(UsdGeom.Tokens.inherited)


# ---------------------------------------------------------------------------
# The character controller's own settings
# ---------------------------------------------------------------------------
#: Defaults, used when config/scene.yaml carries no ``avatar.controller`` block.
#: Every one of these is a measured choice; see apply_controller_tuning.
CONTROLLER_DEFAULTS = {
    "step_offset": 0.04,
    "slope_limit_deg": 40.0,
    "contact_offset": 0.02,
    "climbing_mode": "constrained",
    "non_walkable_mode": "preventClimbing",
}


def slope_limit_cosine(degrees: float) -> float:
    """Degrees in, schema value out. **`slopeLimit` is a COSINE.**

    PhysxSchema's own doc: "Slope limit which the CCT can climb. The limit is
    expressed as the cosine of the desired limit angle. A value of 0 disables
    this feature." So 0.5 is not a small number, it is **60 degrees**, and
    raising the value makes the controller *stricter*, not looser. The config
    declares degrees for that reason.
    """
    import math

    d = max(0.0, min(89.9, float(degrees)))
    return float(math.cos(math.radians(d)))


def apply_controller_tuning(body_prim: Usd.Prim, controller: dict | None = None) -> dict:
    """Write step offset, slope limit, climbing mode and contact offset.

    WHY EACH NUMBER, all measured on this stage 2026-09-02.

    ``step_offset = 0.04`` -- the maximum height of an obstacle the character
    can climb. The scene decides where this belongs, and it leaves an empty
    band to put it in. Every collider resting on the floor within 14 m of the
    spawn point, by height::

        0.005-0.025 m   9   SM_PaperNote_Small_*   sheets of paper
        --------------------  nothing at all between 0.025 and 0.061  --------
        0.061 m         4   SM_BottlePlasticD_*
        0.080 m         1   SM_CratePlastic_E_03
        0.137 m         2   SM_CratePlasticNote_B_*
        0.149 m         1   SM_CardBoxD_04
        0.211 m        27   SM_PaletteA_*          pallets

    0.04 sits in the middle of that gap: it steps over all nine paper notes and
    stops at everything from the bottles up. The value it replaces was
    **0.01**, which is below the paper -- the avatar was being stopped dead by
    sheets of A4, which is the "too low catches on floor decals" failure in its
    literal form. Anything above 0.061 starts levitating over litter and above
    0.137 over the crates.

    ``slope_limit_deg = 40`` -- cos(40 deg) = 0.766, replacing 0.5, which is
    **60 degrees**. A warehouse floor is flat; 40 degrees is already generous
    for a walking person and it makes the flank of a drum non-walkable.

    ``climbing_mode = "constrained"`` -- and this is the one that matters for
    "the avatar climbs onto a barrel". PhysX's default ``easy`` lets the capsule
    climb over an obstacle according to the impact normal **regardless of the
    step offset**; ``constrained`` limits it to the step offset. The step offset
    was already 0.01 m when the avatar was riding a 0.42 m drum, so the step
    offset was never the mechanism -- this was.

    THE ONE THING THIS CANNOT FIX BY ITSELF: ``OgnCharacterController`` builds
    ``CharacterController(path, cam, gravity, 0.01)`` and its ``activate()``
    does ``GetStepOffsetAttr().Set(0.01)`` on 'Simulation Start Play'. So the
    graph overwrites ``stepOffset`` -- and only ``stepOffset`` -- every time you
    press Play. :func:`install_controller_tuning` is what puts it back.
    """
    from pxr import PhysxSchema

    c = dict(CONTROLLER_DEFAULTS)
    c.update(controller or {})
    api = PhysxSchema.PhysxCharacterControllerAPI(body_prim)
    if not body_prim.HasAPI(PhysxSchema.PhysxCharacterControllerAPI):
        api = PhysxSchema.PhysxCharacterControllerAPI.Apply(body_prim)
    api.CreateStepOffsetAttr().Set(float(c["step_offset"]))
    api.CreateSlopeLimitAttr().Set(slope_limit_cosine(c["slope_limit_deg"]))
    api.CreateContactOffsetAttr().Set(float(c["contact_offset"]))
    api.CreateClimbingModeAttr().Set(str(c["climbing_mode"]))
    api.CreateNonWalkableModeAttr().Set(str(c["non_walkable_mode"]))
    return c


def install_controller_tuning(
    stage: Usd.Stage, avatar_path: str = f"{ROOT}/Avatar", *,
    controller: dict | None = None, frames: int = 120,
):
    """Re-apply the controller settings for a while after every Play.

    KEEP A REFERENCE, like install_character_follow: dropping it unsubscribes.

    Needed because the shipped ``OgnCharacterController`` writes ``stepOffset``
    at Play and the value it writes is 0.01, not ours. Re-applying once on the
    PLAY event is not enough on its own -- the CCT manager builds the PxController
    from the USD attributes in its own stage-update pass and the ordering
    between that and a timeline-event subscriber is not ours to decide -- so
    this rewrites for ``frames`` frames after each PLAY and then stops. One
    attribute compare per frame for two seconds, then nothing.

    **What this does not establish:** that PhysX honours a change made after
    the controller exists. The attribute reads back correctly either way, and
    the only test that separates those two is walking into something, which
    needs the GUI (``set_move`` does not work headlessly on this host -- see
    sim/spikes/FINDINGS.md). Treat the step offset as verified only once a
    human has walked the avatar over a paper note and into a bottle.
    """
    import omni.kit.app
    import omni.timeline

    body = stage.GetPrimAtPath(f"{avatar_path}/body_mesh")
    if not body.IsValid():
        print(f"  ! cannot tune the controller: {body.GetPath()} is not valid",
              flush=True)
        return None
    if controller is None:
        try:
            controller = load_avatar_config().get("controller")
        except Exception:                                         # noqa: BLE001
            controller = None
    wanted = apply_controller_tuning(body, controller)
    state = {"left": 0}

    def _on_timeline(e) -> None:
        if e.type == int(omni.timeline.TimelineEventType.PLAY):
            state["left"] = int(frames)

    def _on_update(_e) -> None:
        if state["left"] <= 0:
            return
        state["left"] -= 1
        apply_controller_tuning(body, controller)

    timeline_sub = omni.timeline.get_timeline_interface(
    ).get_timeline_event_stream().create_subscription_to_pop(
        _on_timeline, name="avatar_cct_tuning_timeline")
    update_sub = omni.kit.app.get_app().get_update_event_stream(
    ).create_subscription_to_pop(_on_update, name="avatar_cct_tuning")
    holder = _CctTuning(timeline_sub, update_sub, wanted)
    print(f"  controller tuning installed: step_offset={wanted['step_offset']} m, "
          f"slope_limit={wanted['slope_limit_deg']} deg "
          f"(cos {slope_limit_cosine(wanted['slope_limit_deg']):.4f}), "
          f"climbing={wanted['climbing_mode']}; re-applied for {frames} frames "
          f"after each Play because OgnCharacterController overwrites stepOffset",
          flush=True)
    return holder


class _CctTuning:
    """Holds both subscriptions. Dropping it stops the re-apply."""

    def __init__(self, timeline_sub, update_sub, wanted: dict) -> None:
        self.timeline_sub = timeline_sub
        self.update_sub = update_sub
        self.wanted = wanted

    def close(self) -> None:
        self.timeline_sub = None
        self.update_sub = None


def install_character_follow(
    stage: Usd.Stage, avatar_path: str = f"{ROOT}/Avatar", *,
    animate: bool = True, walk: WalkCycle | None = None,
):
    """Make the visible character track the collision capsule, every frame.

    Python rather than OmniGraph, because OmniGraph cannot see the capsule
    move. The character controller writes its pose to USD; Fabric is never
    updated; ReadPrimAttribute reads Fabric and therefore returns the value it
    cached at setup, forever. Measured: 130 computes, 130 identical values,
    while the capsule travelled 2.58 m. See sim/spikes/_diag_follow_graph.py.

    This is the shipped shape for the problem -- omni.physxcct's own
    first-person camera follows this same capsule with a per-frame callback
    reading UsdGeom.XformCache.

    ALSO DRIVES THE WALK CYCLE, unless ``animate=False``. Not a second
    subscription, because this one already has the only thing a gait needs:
    it reads the capsule's world position every frame in order to copy it, and
    the difference between this frame's position and last frame's IS how far
    the avatar walked. Splitting them would mean reading the same transform
    twice per frame and, worse, allowing the two to disagree about where the
    avatar is on the frame one of them was installed and the other was not.

    ``animate=False`` leaves the character posed exactly as the asset ships it.
    **It is not a performance lever.** It was documented as one on the
    strength of a +15.9 ms/frame figure that turned out to be the annotator
    readback in the measuring spike rather than anything the gait did;
    re-measured against its own controls the same day, the gait costs
    **-0.55 ms/frame** against the
    shipped idle, which is to say nothing -- the character is re-skinned every
    frame either way, because the Worker ships a 582-sample idle clip and Play
    advances the timeline. Turn it off to see the asset's own pose, not to buy
    frame rate; there is none to buy. See ``sim/spikes/FINDINGS.md``,
    "the frame-rate cost -- RETRACTED THE SAME DAY".

    Returns the subscription, which carries the ``WalkCycle`` on
    ``sub.walk_cycle`` for a caller that wants to read the phase back. KEEP A
    REFERENCE: dropping it unsubscribes and the character silently stops
    following.
    """
    import omni.kit.app

    body = stage.GetPrimAtPath(f"{avatar_path}/body_mesh")
    char = stage.GetPrimAtPath(f"{avatar_path}/character")
    if not body.IsValid() or not char.IsValid():
        print(f"  ! cannot install follow: {body.IsValid()=} {char.IsValid()=}", flush=True)
        return None

    attr = char.GetAttribute("xformOp:translate")
    if not attr:
        attr = UsdGeom.Xform(char).AddTranslateOp().GetAttr()
    cache = UsdGeom.XformCache()

    cycle = walk
    if animate and cycle is None:
        try:
            cycle = WalkCycle(stage, avatar_path)
        except Exception as exc:                                  # noqa: BLE001
            print(f"  ! walk cycle unavailable: {exc!r}", flush=True)
            cycle = None
    if cycle is not None and not cycle.ok:
        print(f"  ! walk cycle not running: {cycle.why} -- the character will "
              f"follow the capsule but its legs will not move", flush=True)

    def _follow(_e) -> None:
        # Clear() every frame or the cache returns the pose it saw first --
        # the same staleness, one layer down.
        cache.Clear()
        t = cache.GetLocalToWorldTransform(body).ExtractTranslation()
        attr.Set(Gf.Vec3d(float(t[0]), float(t[1]), float(t[2])))
        if cycle is not None and cycle.ok:
            # After the translate, not before: the gait reads the position it
            # was just moved to, so phase and pose belong to the same frame.
            cycle.update((float(t[0]), float(t[1])))

    sub = omni.kit.app.get_app().get_update_event_stream().create_subscription_to_pop(
        _follow, name="avatar_character_follow"
    )
    # Carried on the subscription so a caller that kept the one reference it
    # was told to keep also has the gait, without a second thing to hold.
    try:
        sub.walk_cycle = cycle
    except Exception as exc:                                      # noqa: BLE001
        # A carb subscription is a C++ binding and need not accept a Python
        # attribute. Losing the convenience is not losing the gait -- the
        # closure above holds the only reference that matters.
        print(f"  (walk cycle not attached to the subscription: {exc!r})", flush=True)
    print(f"  character follow installed: {body.GetPath()} -> {char.GetPath()}"
          + (f" (walk cycle on {len(cycle.driven)} joints)"
             if cycle is not None and cycle.ok else " (no walk cycle)"),
          flush=True)
    return sub


# ---------------------------------------------------------------------------
# The walk cycle
# ---------------------------------------------------------------------------
# WHY THIS IS AUTHORED MOTION AND NOT A SHIPPED CLIP, WHICH IS NOT WHAT RULE 4
# WANTS AND IS WHAT THE ASSETS ALLOW. Measured 2026-08-26,
# sim/spikes/_diag_walk_clip.py:
#
#   the avatar's skeleton      101 joints, RL_BoneRoot/Hip/Pelvis/L_Thigh/...
#   Isaac/People/Animations    stand_walk_loop_in_place and every other clip:
#                              81 joints, Root/Pelvis/R_UpLeg/R_LoLeg/...
#   overlap                    ZERO. Not "a different order" -- no joint name
#                              in the walk clip exists on this skeleton.
#
# This contradicts the 2026-08-17 scoping note, which called the walk "a
# reference swap plus a blend, NOT retargeting". That note compared People's
# CHARACTERS to the Worker and found 101 matching joints, then inferred the
# clips beside them matched too, and flagged the inference as unproven. It was
# wrong: People's characters are on the Worker's skeleton (re-measured here --
# male_adult_construction_01 is RL_BoneRoot, 101 joints) and People's clips are
# not, so those clips do not fit their own characters either without a
# retarget step.
#
# Nor does one ship elsewhere. Every walk-shaped asset within reach was listed:
#
#   Reallusion/Worker/Motions       Kitchen_CleanTable, Market_Sales_Assisting,
#                                   Market_Sales_SortOut, StandingDiscussion,
#                                   TrafficGuard, Worker_Idle_Pose -- no walk
#   Reallusion/Debra, Orc/Motions   idles, a superpower fist, a sword shout
#   full_warehouse_worker_and_anim_cameras.usd
#                                   the same 101-joint rig carrying the same
#                                   idle: its root travels 0.0042 over the
#                                   whole clip, i.e. sway, not locomotion
#
# `omni.anim.retarget.core` and `omni.anim.graph.core` ARE enabled in this
# image (`omni.anim.people` is not), so retargeting People's motion-captured
# walk onto this skeleton is the principled route to a better-looking cycle
# and is the recommended next step. It is an authoring workflow, it cannot be
# checked without a human looking at it, and it is a bigger job than this one.
#
# What is below instead: the shipped idle clip supplies the whole body's pose,
# and a gait is overlaid on ten joints. So the character still stands, breathes
# and sways as the asset's animator intended, and its legs and arms swing on
# top of that -- driven by DISTANCE TRAVELLED, so the cycle cannot drift out of
# step with the ground no matter what the frame rate does.

#: Joints the gait drives, matched by the LAST component of the joint path so
#: that a rig which re-parents an arm still resolves. Everything else keeps the
#: shipped clip's pose exactly.
_GAIT_JOINTS = ("L_Thigh", "R_Thigh", "L_Calf", "R_Calf",
                "L_Foot", "R_Foot", "L_Upperarm", "R_Upperarm",
                "L_Forearm", "R_Forearm")

#: Peak swing, degrees, at full walking speed. A human hip swings roughly
#: +/-20 deg at a normal pace and the knee flexes about 60 deg through swing;
#: these are at the quiet end of that on purpose, because an overstated gait
#: on a mesh whose feet cannot be checked against the floor reads as a stomp.
_GAIT_AMPLITUDE_DEG = {"Thigh": 22.0, "Calf": 45.0, "Foot": 10.0,
                       "Upperarm": 18.0, "Forearm": 12.0}

#: Metres of ground per complete cycle -- one stride, both feet. This is the
#: number that decides whether the feet skate: the phase advances by
#: distance/this, so at any speed the same fraction of the cycle passes per
#: metre. 1.5 m is a walking adult's stride and it is a CHOICE, not a
#: measurement, because no shipped clip on this skeleton exists to measure one
#: from. It is the first thing to tune if the feet look wrong.
_STRIDE_M = 1.5

#: Speed at which the gait reaches full amplitude, m/s. Below it the swing is
#: scaled down, so a slow shuffle does not throw its legs around; at zero the
#: overlay vanishes entirely and the character is exactly the shipped idle.
_GAIT_FULL_SPEED_MPS = 1.2

#: How quickly measured speed and heading follow the truth. The capsule's
#: position comes from a physics controller and is not smooth; without this the
#: character twitches on every frame where the controller happened to move it
#: slightly less.
_GAIT_SMOOTHING = 0.25

#: Below this, treat the avatar as standing still: do not turn it, do not swing
#: it. A character that spins to face the direction of a millimetre of physics
#: jitter is worse than one that does not turn at all.
_GAIT_MIN_SPEED_MPS = 0.05


def _quatf(q) -> Gf.Quatf:
    """A Gf.Quatf from any precision of Gf quaternion, built component-wise.

    Explicit because the cross-precision constructor is not uniformly bound:
    `Gf.Quatf(Gf.Quatd)` raises here, and `Gf.Rotation` has no Matrix3d
    overload at all, so the tidy-looking spellings of this are the ones that
    fail at runtime.
    """
    i = q.GetImaginary()
    return Gf.Quatf(float(q.GetReal()),
                    Gf.Vec3f(float(i[0]), float(i[1]), float(i[2])))


def _quat(axis, angle_rad: float) -> Gf.Quatf:
    """A quatf rotating `angle_rad` about a (unit) local axis."""
    half = angle_rad * 0.5
    s = math.sin(half)
    a = Gf.Vec3f(axis[0], axis[1], axis[2]).GetNormalized()
    return Gf.Quatf(math.cos(half), Gf.Vec3f(a[0] * s, a[1] * s, a[2] * s))


class WalkCycle:
    """Swing the avatar's legs and arms in step with how far it has walked.

    Reads the capsule's world position every frame, differences it, and turns
    the distance into a phase. Nothing here is driven by wall-clock or by the
    timeline: at 60 fps and at 6 fps the same metre of travel advances the
    cycle by the same amount, which is the property that keeps the feet
    matched to the ground and makes a capture reproducible.

    WHAT IT WRITES, AND WHY EACH IS SAFE
    -------------------------------------
    ``character/anim_walk``   a new SkelAnimation, bound to the existing
                              skeleton. Not renderable geometry, so it changes
                              nothing about segmentation: the meshes that carry
                              the ``person`` label are the ones the asset
                              already shipped and this only poses them.
    ``character`` rotateXYZ   the facing. It has to go here and nowhere else:
                              PhysX owns the capsule and a character controller
                              has a position and an up direction and NO
                              rotation, so a yaw written to the capsule never
                              reaches the renderer (measured 2026-08-26). The
                              character Xform is a prim physics does not own.

    WHAT IT DOES NOT TOUCH: the capsule. Not its transform, not its collision,
    not its visibility. It is the collision representation and what the lidar
    and radar bounce off -- failure mode 1 -- and this class never addresses it
    except to read where it is.

    The gait's swing axis is DERIVED from the rest pose rather than assumed.
    A rotation about the wrong local axis produces a leg that swings sideways,
    which is not an error, does not raise, and looks like a rig bug rather than
    a maths bug. See :meth:`_derive_axes`.
    """

    def __init__(self, stage: Usd.Stage, avatar_path: str = f"{ROOT}/Avatar",
                 *, stride_m: float = _STRIDE_M, verbose: bool = True) -> None:
        from pxr import UsdSkel

        self.stage = stage
        self.ok = False
        self.why = ""
        self.stride_m = float(stride_m)
        self.phase = 0.0
        self.speed = 0.0
        self.heading_deg: float | None = None
        self.last_xy: tuple[float, float] | None = None
        self.distance_m = 0.0
        self.frames = 0

        char_path = f"{avatar_path}/character"
        self.char = stage.GetPrimAtPath(char_path)
        if not self.char.IsValid():
            self.why = f"no character at {char_path}"
            return

        skels = [p for p in Usd.PrimRange(self.char)
                 if p.IsA(UsdSkel.Skeleton)]
        if not skels:
            self.why = f"no UsdSkel.Skeleton under {char_path}"
            return
        self.skel_prim = skels[0]
        skel = UsdSkel.Skeleton(self.skel_prim)
        self.joints = [str(j) for j in (skel.GetJointsAttr().Get() or [])]
        if not self.joints:
            self.why = f"{self.skel_prim.GetPath()} lists no joints"
            return

        # The pose everything else is layered on. Read from whatever the asset
        # had bound BEFORE this class rebinds anything -- that clip is the
        # character standing like a person rather than in its bind pose, which
        # for this rig is a T-pose.
        binding = UsdSkel.BindingAPI(self.skel_prim)
        source = binding.GetAnimationSource()
        self.base_anim = UsdSkel.Animation(source) if source else None
        self.base_joints: list[str] = []
        self.base_rot_attr = None
        if self.base_anim:
            self.base_joints = [str(j) for j in
                                (self.base_anim.GetJointsAttr().Get() or [])]
            self.base_rot_attr = self.base_anim.GetRotationsAttr()
        self.base_times = (list(self.base_rot_attr.GetTimeSamples())
                           if self.base_rot_attr else [])
        #: our joint index -> index into the shipped clip's arrays, or -1.
        #: Built once. Rebuilding it per frame is 101 dict lookups a frame for
        #: an answer that cannot change.
        self.base_index: list[int] = []
        self._last_written: tuple | None = None

        try:
            self._derive_axes()
        except Exception as exc:                                  # noqa: BLE001
            self.why = f"could not derive the swing axes: {exc!r}"
            return
        if not self.driven:
            self.why = ("none of the gait's joints are on this skeleton: "
                        f"looked for {list(_GAIT_JOINTS)}")
            return

        idx = {name: i for i, name in enumerate(self.base_joints)}
        self.base_index = [idx.get(name, -1) for name in self.joints]
        #: The rest pose as quaternions, computed once. This used to be
        #: rebuilt every frame -- 101 matrix decompositions for a constant.
        self.rest_quats = [_quatf(m.ExtractRotationQuat())
                           for m in self.rest_local]
        try:
            self._author_animation(char_path)
        except Exception as exc:                                  # noqa: BLE001
            self.why = f"could not author the animation: {exc!r}"
            return
        self.ok = True
        if verbose:
            print(f"  walk cycle: {len(self.driven)} joints driven "
                  f"({', '.join(sorted(self.driven))}), stride {self.stride_m} m, "
                  f"base pose from "
                  f"{self.base_anim.GetPrim().GetPath() if self.base_anim else '<rest>'}",
                  flush=True)

    # -- setup ------------------------------------------------------------
    def _derive_axes(self) -> None:
        """Find, per joint, the local axis whose rotation swings it FORWARD.

        Not assumed, because assuming it is invisible when wrong. A hip
        rotated about the wrong local axis abducts instead of flexing -- the
        leg swings out sideways -- and that renders as a broken rig, raises
        nothing, and is indistinguishable from a bad asset until somebody
        looks.

        Two measurements off the skeleton's own rest pose:

        1. **the axis.** Walking happens in the sagittal plane, so the swing
           axis is the body's left-right axis. Expressed in the joint's own
           frame that is ``R_rest^-1 * lateral``, and R_rest comes from the
           rest transforms the asset ships.
        2. **the sign.** Rotating +theta about that axis swings the limb one
           way and nobody knows which. So: rotate the joint by a small test
           angle, run the rest of the chain forward, and see which way the end
           of the limb actually moved. If it went backwards, flip.

        The rig faces -Y in its own space (``_ASSET_FACING_DEG``, itself
        measured off the ankle and toe joints), so lateral is -Y x +Z.
        """
        from pxr import UsdSkel

        skel = UsdSkel.Skeleton(self.skel_prim)
        topo = UsdSkel.Topology(self.joints)
        rest = skel.GetRestTransformsAttr().Get()
        if rest is None or len(rest) != len(self.joints):
            raise RuntimeError(
                f"restTransforms has {0 if rest is None else len(rest)} entries "
                f"for {len(self.joints)} joints -- cannot run the chain forward")
        self.rest_local = [Gf.Matrix4d(m) for m in rest]

        # Rest pose in skeleton space, by walking parents. UsdSkel guarantees
        # a joint's parent precedes it, so one pass in order is enough.
        parents = [topo.GetParent(i) for i in range(len(self.joints))]
        world = []
        for i, m in enumerate(self.rest_local):
            p = parents[i]
            world.append(m if p < 0 else m * world[p])
        self.rest_world = world
        self.parents = parents

        facing = Gf.Vec3d(0.0, -1.0, 0.0)      # the toes lead -Y; measured
        up = Gf.Vec3d(0.0, 0.0, 1.0)
        lateral = Gf.Cross(facing, up).GetNormalized()

        # index of every joint whose path ends in a name the gait drives
        by_name: dict[str, int] = {}
        for i, path in enumerate(self.joints):
            by_name.setdefault(path.rsplit("/", 1)[-1], i)
        self.driven: dict[str, int] = {n: by_name[n] for n in _GAIT_JOINTS
                                       if n in by_name}
        # the tip whose motion decides the sign: for a leg the foot, for an
        # arm the forearm. Falls back to the joint itself.
        tips = {"L_Thigh": "L_Foot", "R_Thigh": "R_Foot",
                "L_Calf": "L_Foot", "R_Calf": "R_Foot",
                "L_Upperarm": "L_Forearm", "R_Upperarm": "R_Forearm"}

        self.axis: dict[str, Gf.Vec3f] = {}
        self.sign: dict[str, float] = {}
        for name, idx in self.driven.items():
            rot = self.rest_world[idx].ExtractRotationMatrix()
            # Row-vector convention, which is USD's: v_world = v_local * R, so
            # v_local = v_world * R^T. Written this way round on purpose --
            # the other order compiles, runs, and swings the leg sideways.
            local_axis = lateral * rot.GetTranspose()
            if local_axis.GetLength() < 1e-9:
                local_axis = Gf.Vec3d(1.0, 0.0, 0.0)
            local_axis = local_axis.GetNormalized()
            self.axis[name] = Gf.Vec3f(*[float(v) for v in local_axis])

            tip_name = tips.get(name, name)
            tip = by_name.get(tip_name, idx)
            before = self.rest_world[tip].ExtractTranslation()
            after = self._tip_after_test_rotation(idx, tip, local_axis, math.radians(10.0))
            moved = Gf.Vec3d(after - before)
            self.sign[name] = 1.0 if (moved * facing) >= 0.0 else -1.0

    def _tip_after_test_rotation(self, idx: int, tip: int,
                                 local_axis, angle_rad: float):
        """Where `tip` ends up if joint `idx` is rotated by the test angle."""
        m = Gf.Matrix4d().SetRotate(
            Gf.Rotation(Gf.Vec3d(local_axis), math.degrees(angle_rad)))
        # Recompute only the chain from idx down to tip.
        chain = []
        j = tip
        while j >= 0:
            chain.append(j)
            if j == idx:
                break
            j = self.parents[j]
        chain.reverse()
        acc = (self.rest_world[self.parents[idx]]
               if self.parents[idx] >= 0 else Gf.Matrix4d(1.0))
        for j in chain:
            local = self.rest_local[j]
            if j == idx:
                local = m * local
            acc = local * acc
        return acc.ExtractTranslation()

    def _author_animation(self, char_path: str) -> None:
        """Create the SkelAnimation this class writes, and bind it."""
        from pxr import UsdSkel

        anim_path = f"{char_path}/anim_walk"
        self.anim = UsdSkel.Animation.Define(self.stage, anim_path)
        # token[], not SdfPath[]. UsdSkel matches an animation to a skeleton
        # by joint NAME, and the names are tokens even though they read as
        # paths; handing it paths raises a type mismatch at Set() time.
        self.anim.CreateJointsAttr().Set(Vt.TokenArray(self.joints))

        # Translations and scales come from the rest pose and never change:
        # a gait is rotation. Authoring them anyway because UsdSkel wants a
        # complete animation, and a missing array is a silent fallback to the
        # bind pose for every joint rather than an error.
        t, sc = [], []
        for m in self.rest_local:
            t.append(Gf.Vec3f(*[float(v) for v in m.ExtractTranslation()]))
            row = [Gf.Vec3d(m[i][0], m[i][1], m[i][2]).GetLength() for i in range(3)]
            sc.append(Gf.Vec3h(*[float(v) for v in row]))
        self.anim.CreateTranslationsAttr().Set(t)
        self.anim.CreateScalesAttr().Set(sc)
        self.rot_attr = self.anim.CreateRotationsAttr()
        self._write_rotations(self._base_rotations(0.0))

        # Bind on the SKELETON itself. `skel:animationSource` resolves to the
        # nearest authored opinion at or above the prim, so binding here beats
        # whatever the referenced asset bound further up, without editing it.
        UsdSkel.BindingAPI.Apply(self.skel_prim).CreateAnimationSourceRel(
        ).SetTargets([Sdf.Path(anim_path)])

    def _write_rotations(self, rots) -> None:
        """Author `rots` onto the SkelAnimation. The ONLY place that happens.

        A one-line indirection with one caller reads like an accident, so:
        it is the seam ``sim/spikes/_diag_walk_timesample.py`` overrides in
        order to author TIME SAMPLES instead of a value at the default time
        code. That is the one structural difference between this animation
        and the shipped clip it rebinds -- the Worker's idle carries 582 time
        samples on `rotations` and no default -- and it was the leading
        candidate for a 15.9 ms/frame cost attributed to binding.

        MEASURED 2026-08-26, and the answer is no in both directions: time
        samples cost **+0.01 ms/frame**, and there was no 15.9 ms to recover
        in the first place. Authoring at the default time code stays.
        """
        self.rot_attr.Set(rots)

    # -- per frame ---------------------------------------------------------
    def _base_rotations(self, when: float):
        """The shipped clip's pose at `when`, as a list indexed like `joints`.

        Falls back to the rest pose for any joint the clip does not animate,
        which is the same thing UsdSkel would have done.
        """
        rest = self.rest_quats
        if not (self.base_rot_attr and self.base_joints):
            return list(rest)
        sample = self.base_rot_attr.Get(Usd.TimeCode(when))
        if sample is None or len(sample) != len(self.base_joints):
            return list(rest)
        return [sample[j] if j >= 0 else rest[i]
                for i, j in enumerate(self.base_index)]

    def _gait_offset(self, name: str, weight: float) -> Gf.Quatf | None:
        """The swing to add to one joint at the current phase, or None."""
        if weight <= 0.0:
            return None
        theta = self.phase * 2.0 * math.pi
        side = -1.0 if name.startswith("R_") else 1.0     # legs alternate
        kind = name.split("_", 1)[-1]
        amp = math.radians(_GAIT_AMPLITUDE_DEG.get(kind, 0.0)) * weight
        if amp <= 0.0:
            return None

        if kind == "Thigh":
            angle = amp * math.sin(theta + (0.0 if side > 0 else math.pi))
        elif kind == "Calf":
            # A knee only bends one way. Peak flexion sits a quarter cycle
            # after the thigh's most-rearward point, which is when the foot is
            # being picked up; -amp because flexion is heel-towards-buttock,
            # the opposite sense to the hip's forward swing.
            angle = -amp * max(0.0, math.sin(
                theta + (0.0 if side > 0 else math.pi) + math.pi * 0.5))
        elif kind == "Foot":
            angle = amp * math.sin(theta + (0.0 if side > 0 else math.pi)
                                   + math.pi)
        else:
            # Arms counter-swing against the leg on the SAME side, which is
            # what makes a walk read as a walk rather than a march.
            angle = amp * math.sin(theta + (math.pi if side > 0 else 0.0))
        return _quat(self.axis[name], angle * self.sign[name])

    def update(self, world_xy, dt: float | None = None) -> dict:
        """Advance the cycle to wherever the avatar now is. Main thread.

        Returns what it did, so a caller can log or assert on it rather than
        inferring the state of the animation from a picture.
        """
        if not self.ok:
            return {"ok": False, "why": self.why}
        self.frames += 1
        x, y = float(world_xy[0]), float(world_xy[1])
        step = 0.0
        if self.last_xy is not None:
            dx, dy = x - self.last_xy[0], y - self.last_xy[1]
            step = math.hypot(dx, dy)
            self.distance_m += step
            # Phase is DISTANCE, not time. Two frames that cover the same
            # ground advance the cycle equally however long they took.
            self.phase = (self.phase + step / max(self.stride_m, 1e-6)) % 1.0
            inst = step / dt if dt and dt > 0 else step * 60.0
            self.speed += (inst - self.speed) * _GAIT_SMOOTHING
            if step > _GAIT_MIN_SPEED_MPS * (dt or 1.0 / 60.0):
                want = math.degrees(math.atan2(dy, dx))
                if self.heading_deg is None:
                    self.heading_deg = want
                else:
                    d = (want - self.heading_deg + 180.0) % 360.0 - 180.0
                    self.heading_deg += d * _GAIT_SMOOTHING
        self.last_xy = (x, y)

        weight = max(0.0, min(1.0, self.speed / _GAIT_FULL_SPEED_MPS))
        # Keep the shipped idle running underneath, so a standing avatar still
        # breathes instead of freezing into a mannequin. Indexed by frame into
        # the clip's own sample times rather than computed from a span, so a
        # clip that does not start at 0 or is not sampled every frame still
        # plays every pose it has and no pose it does not.
        timeline_now = (self.base_times[self.frames % len(self.base_times)]
                        if self.base_times else 0.0)
        # Skip a write that would author the pose already authored. Kept, and
        # by now for neither of the reasons it has been given. It went in
        # expecting the write to be the expensive part. A three-way
        # measurement then said the cost was all in BINDING a different
        # animation -- 17.37 ms/frame shipped, 33.30 ours bound and never
        # written -- and that was wrong too: those two rows differed in
        # whether the arm read the annotator back, not in what was bound.
        # Re-measured against its own controls (_diag_walk_timesample.py,
        # 2026-08-26): binding costs +0.01 ms, writing every frame costs
        # -0.55, and the 16 ms was `annotator.get_data()`. NOTHING HERE IS
        # EXPENSIVE. So this saves nothing measurable and is worth keeping
        # only because a pose that has not changed has no business being
        # re-authored.
        key = (round(self.phase, 4) if weight > 0 else None,
               round(weight, 3), timeline_now)
        if key == self._last_written:
            return {"ok": True, "phase": round(self.phase, 4),
                    "speed_mps": round(self.speed, 4), "weight": round(weight, 3),
                    "distance_m": round(self.distance_m, 3), "skipped": True,
                    "heading_deg": (None if self.heading_deg is None
                                    else round(self.heading_deg, 2))}
        self._last_written = key

        rots = self._base_rotations(timeline_now)
        for name, idx in self.driven.items():
            offset = self._gait_offset(name, weight)
            if offset is not None:
                rots[idx] = rots[idx] * offset
        self._write_rotations(rots)

        if self.heading_deg is not None:
            self._face(self.heading_deg)
        return {"ok": True, "phase": round(self.phase, 4),
                "speed_mps": round(self.speed, 4), "weight": round(weight, 3),
                "distance_m": round(self.distance_m, 3),
                "heading_deg": (None if self.heading_deg is None
                                else round(self.heading_deg, 2))}

    def _face(self, heading_deg: float) -> None:
        """Turn the visible body to `heading_deg`, the way set_avatar_pose does.

        The same derivation, deliberately: the rig's own yaw offset is read off
        the stage and subtracted, so the two entry points cannot drift apart
        into an avatar that faces one way when it is placed and another way
        when it walks.
        """
        rig = self.stage.GetPrimAtPath(f"{self.char.GetPath()}/rig")
        rig_yaw = _CHARACTER_YAW_DEG
        rig_rot = rig.GetAttribute("xformOp:rotateXYZ") if rig.IsValid() else None
        if rig_rot and rig_rot.Get() is not None:
            rig_yaw = float(rig_rot.Get()[2])
        attr = self.char.GetAttribute("xformOp:rotateXYZ")
        if not attr:
            attr = UsdGeom.Xformable(self.char).AddRotateXYZOp().GetAttr()
        current = attr.Get() or Gf.Vec3f(0.0, 0.0, 0.0)
        attr.Set(Gf.Vec3f(float(current[0]), float(current[1]),
                          heading_deg - (_ASSET_FACING_DEG + rig_yaw)))


# ---------------------------------------------------------------------------
# Runtime pose control -- the second entry point, alongside the keyboard
# ---------------------------------------------------------------------------
def _cct_extension_enabled() -> bool:
    """Is ``omni.physx.cct`` enabled in THIS process?

    The discriminator for whether :func:`set_avatar_pose` has a controller to
    talk to at all.

    NOT the same question as "did the launch line pass ``--enable
    omni.physx.cct``". MEASURED 2026-08-26: ``runheadless.sh`` starts
    ``omni.physx.cct`` on its own -- it appears in the extension startup log of
    a plain ``--exec`` run that passed no such flag. The elsewhere-recorded
    belief that no shipped experience enables it holds for ``python.sh``, not
    for this launcher. Ask the extension manager; do not infer it from argv.
    """
    try:
        import omni.kit.app

        mgr = omni.kit.app.get_app().get_extension_manager()
        return bool(mgr.is_extension_enabled("omni.physx.cct"))
    except Exception:
        return False


def _yaw_attr_value(attr, angle_deg: float):
    """A quaternion of `angle_deg` about +Z, in whatever precision `attr` is.

    ``AddOrientOp()`` authors ``quatf`` and that is what sim/avatar.py builds,
    but a stage that arrived any other way may hold ``quatd``, and setting the
    wrong one raises rather than converting.
    """
    half = math.radians(angle_deg) / 2.0
    if attr.GetTypeName() == Sdf.ValueTypeNames.Quatd:
        return Gf.Quatd(math.cos(half), Gf.Vec3d(0.0, 0.0, math.sin(half)))
    return Gf.Quatf(math.cos(half), Gf.Vec3f(0.0, 0.0, math.sin(half)))


def set_avatar_pose(
    stage: Usd.Stage,
    position,
    yaw_deg: float | None = None,
    *,
    avatar_path: str = f"{ROOT}/Avatar",
    verbose: bool = False,
) -> dict:
    """Place the avatar at `position` facing `yaw_deg`. Repeatable, no restart.

    The entry point episode reset needs. The keyboard stays exactly as it was:
    nothing here touches the Controls graph, deactivates the character
    controller, or unbinds an action, so W/A/S/D keeps working and simply
    carries on from wherever this put the avatar.

    THROUGH THE CHARACTER CONTROLLER, OR AROUND IT?
    -----------------------------------------------
    **Both, and which one is not a preference -- it is whichever one is not a
    silent no-op in the caller's process.** Each single-route design has its
    own way of doing nothing while looking correct:

      * **USD write alone, with the CCT active.** Physics owns this prim while
        it is being simulated and writes its own answer back over what you
        authored. That it does so is measured, not supposed: the capsule's
        authored z of 0.925 becomes 0.895 within a few frames of Play, and the
        yaw written to its ``orient`` is put back to identity every frame (see
        the yaw block below). A translation the controller disagreed with
        would go the same way, and it would look like a pose write that worked
        and then quietly un-worked.
      * **``set_position()`` alone, with the CCT inactive.** There is then no
        controller registered for this path, the call lands nowhere, and the
        avatar does not move at all.

    So this writes the USD transform first -- authoritative when nothing else
    owns the capsule -- and then, if and only if the extension is enabled,
    also asks the controller to place itself at the same point via
    ``omni.physxcct``'s ``set_position()``. The two never disagree, because
    they are handed the same number.

    Note which of those two the project actually runs in, because it is not
    what the code around it assumes: **``runheadless.sh`` starts
    ``omni.physx.cct`` on its own**, with no ``--enable`` flag anywhere on the
    line. Measured 2026-08-26 from the extension startup log of a plain
    ``--exec`` run. So a headless capture is the *first* case, not the second,
    and ``sim/observation_adapter.py``'s note that its driver "runs WITHOUT
    ``--enable omni.physx.cct``, so the character-controller node type stays
    unregistered and nothing contends for the capsule's transform" does not
    hold under that launcher. Nothing here depends on which case it is --
    that is the point of doing both -- but do not read the flag and conclude.

    **Neither route is collide-and-slide, and that is the caveat this function
    inherits.** Collide-and-slide is what ``set_move()`` does -- the shipped
    keyboard path, a swept move that stops against a shelf. ``set_position()``
    is a different entry point: a placement, not a sweep. So a pose written
    here can be a pose no walk could have reached, and can put the capsule
    inside static geometry. Whether PhysX depenetrates a controller that lands
    there on its next ``move()`` is **not something this project has
    measured** -- do not assume it does. The existing statement of the same
    caveat is in ``sim/spikes/FINDINGS.md``, about the scripted circuit walk
    the S11 contract run uses: "a scripted walk, not CCT collide-and-slide --
    it says nothing about the character controller". This function does not
    change that; it makes the pose write deliberate and reusable instead of
    something each driver reimplements.

    WHAT IT WRITES, AND WHY IT IS FOUR PRIMS AND NOT ONE
    -----------------------------------------------------
    ``body_mesh``   translate + orient. The capsule is what physics moves.
                    Yaw about the up axis leaves a Z-axis capsule's collision
                    shape identical, so the orient costs nothing -- but see
                    the note in the code: with the timeline playing it does
                    not survive, because PhysX owns this prim's rotation and a
                    character controller has no rotation to own.
    the cameras     rotateXYZ, on every ``UsdGeom.Camera`` under the capsule,
                    pitch preserved. This is what actually turns the view, and
                    it is what an observation depends on.
    ``character``   translate + rotateXYZ. The visible rigged body -- and what
                    RTX lidar, radar and cameras actually trace, since they
                    see RENDER geometry, not colliders. Written directly
                    rather than left to :func:`install_character_follow` so
                    the pose is coherent in the SAME frame: a sensor read on
                    the next tick must not see the body still standing where
                    the episode used to start. The follow then writes the same
                    translate again next frame, which is a no-op.

    WHAT A CALLER OWES AFTER CALLING THIS: FRAMES
    ----------------------------------------------
    The pose is in USD the instant this returns. **The sensors are not.**
    Measured 2026-08-26 with ``sim/verify_avatar_pose.py``: the fixed
    station's camera tracks a pose write immediately, and its RTX lidar's
    point cloud keeps describing the PREVIOUS pose for **5 to 10 frames**
    afterwards -- a whole waypoint's worth, at three waypoints out of three.

    This is the shape of failure mode 10 one layer along, and it is worse than
    an empty buffer: a cloud of the wrong moment is a perfectly well-formed
    cloud, with the right density, the right extent, and returns on a body
    that is genuinely there -- just not where the episode says it is. An
    episode reset that samples immediately therefore records its first
    observations against the END of the previous episode.

    So: write the pose, spend frames, then sample. The verification script
    budgets 30 and reports the crossover frame every run rather than trusting
    the number, which is what the number is worth.

    One thing it deliberately does NOT do: orbit the third-person camera's
    MOUNT POINT. That camera sits 3 m along the capsule's local -X, and while
    physics is holding the capsule at identity there is no rotation for that
    offset to ride. Yaw turns what it looks along, not where it stands, so at
    yaw far from the built heading it becomes a side view rather than a chase
    view. Fixing that means writing the camera's translate too, which is a
    change to where a declared sensor is mounted -- a registry decision, not
    something a pose setter should make on its own.

    Args:
        stage: The stage the avatar is on.
        position: ``(x, y)`` or ``(x, y, z)`` in world **metres**. Two
            components keep the capsule's current standing height, which is
            what an episode reset almost always wants. Three set it
            explicitly, and z is the **capsule centre**, not the feet:
            ``centre = feet + height/2`` for the capsule this module builds.
        yaw_deg: Heading in degrees about +Z, 0 = world +X, counter-clockwise
            positive, applied to the cameras and the visible body alike.
            ``None`` leaves the current heading untouched.
        avatar_path: Root of the avatar rig. Read from the stage, never
            invented (hard rule 1) -- every prim below it must already exist.
        verbose: Print what was written. Off by default: an episode reset runs
            thousands of times.

    Returns:
        What was actually done, for a caller that needs to log or assert on it
        -- including which routes ran, so "the pose write did nothing" is
        answerable from the record rather than by re-deriving it.

    Raises:
        RuntimeError: the rig is not where it says it is, the stage is not
            Z-up, or ``avatar_path`` is not at identity (see below).
        ValueError: `position` is not 2 or 3 components.
    """
    body_path = f"{avatar_path}/body_mesh"
    body = stage.GetPrimAtPath(body_path)
    char = stage.GetPrimAtPath(f"{avatar_path}/character")
    if not body.IsValid():
        raise RuntimeError(
            f"no capsule at {body_path} -- set_avatar_pose() only moves an "
            f"avatar that sim/avatar.py built"
        )
    if UsdGeom.GetStageUpAxis(stage) != UsdGeom.Tokens.z:
        raise RuntimeError(
            "set_avatar_pose() writes yaw about +Z and treats index 2 as "
            "vertical; this stage is not Z-up"
        )

    # /Root/Avatar is deliberately identity (see the module docstring), and a
    # non-identity parent would silently make every number below a LOCAL pose
    # wearing a world pose's name. Refuse rather than convert: converting the
    # translation is easy and converting the caller's intent for yaw is not.
    parent_to_world = UsdGeom.Xformable(body).ComputeParentToWorldTransform(
        Usd.TimeCode.Default())
    identity = Gf.Matrix4d(1.0)
    skew = max(abs(parent_to_world[i][j] - identity[i][j])
               for i in range(4) for j in range(4))
    if skew > 1e-6:
        raise RuntimeError(
            f"{avatar_path} is not at identity (max element delta {skew:.6g}). "
            f"set_avatar_pose() writes world poses onto the capsule's LOCAL "
            f"transform, which is only the same thing while the Avatar Xform "
            f"stays at identity -- as sim/avatar.py builds it and as the "
            f"character controller requires."
        )

    # Poses cross this boundary in metres (core/observation.py LENGTH_UNIT);
    # USD holds stage units. Same conversion sim/observation_adapter.py makes
    # in the other direction, and the same silent factor of 100 if skipped.
    mpu = float(UsdGeom.GetStageMetersPerUnit(stage) or 1.0)

    t_attr = body.GetAttribute("xformOp:translate")
    if not t_attr:
        t_attr = UsdGeom.Xformable(body).AddTranslateOp().GetAttr()
    current = t_attr.Get() or Gf.Vec3d(0.0, 0.0, 0.0)

    vals = [float(v) for v in position]
    if len(vals) == 2:
        x_u, y_u = vals[0] / mpu, vals[1] / mpu
        z_u = float(current[2])
    elif len(vals) == 3:
        x_u, y_u, z_u = (v / mpu for v in vals)
    else:
        raise ValueError(
            f"position must be (x, y) or (x, y, z) in metres, got {len(vals)} "
            f"components"
        )
    target = Gf.Vec3d(x_u, y_u, z_u)
    t_attr.Set(target)

    report: dict = {
        "position_m": (x_u * mpu, y_u * mpu, z_u * mpu),
        "yaw_deg": None if yaw_deg is None else float(yaw_deg),
        "avatar_path": avatar_path,
        "usd_write": True,
        "character_written": False,
        "cct_extension_enabled": _cct_extension_enabled(),
        "cct_set_position": "not attempted (omni.physx.cct is not enabled)",
        "via_character_controller": False,
    }

    # --- yaw: three prims, because only two of them survive physics --------
    char_rotate_z = None
    if yaw_deg is not None:
        yaw = float(yaw_deg)
        o_attr = body.GetAttribute("xformOp:orient")
        if not o_attr:
            o_attr = UsdGeom.Xformable(body).AddOrientOp().GetAttr()
        # The cameras are already aimed along _DEFAULT_HEADING_DEG by their
        # authored rotateXYZ, so the capsule only carries the DIFFERENCE.
        o_attr.Set(_yaw_attr_value(o_attr, yaw - _DEFAULT_HEADING_DEG))

        # ...and then aim each camera itself, which is NOT belt and braces.
        #
        # MEASURED 2026-08-26, and it is a silent one: with the timeline
        # PLAYING, the write above never reaches the renderer. The capsule
        # carries PhysxCharacterControllerAPI, so PhysX simulates it as a
        # character controller -- and a PhysX controller has a position and an
        # up direction and no orientation at all, so its per-frame writeback
        # puts identity back over whatever was authored. Nothing raises, and
        # the ATTRIBUTE ITSELF reads back as (1, 0, 0, 0) -- so this is not a
        # Fabric-versus-USD problem you could work around by reading somewhere
        # else. Four waypoints commanding 0/90/-90/0 deg produced a
        # first-person camera heading of 0.00 deg at every single one, while
        # the character -- which PhysX does not touch -- turned by exactly the
        # commanded angle each time.
        #
        # So the heading has to live on a prim physics does not own. The
        # cameras are those prims. This is also the only half that matters to
        # an observation: what the avatar SEES is the camera's own aim.
        #
        # The capsule write above is kept because it is correct and effective
        # wherever physics is not simulating the capsule -- a stopped
        # timeline, or a stage without the CCT schema applied -- and because
        # it costs one attribute.
        aimed = []
        for child in body.GetChildren():
            if not child.IsA(UsdGeom.Camera):
                continue
            r_attr = child.GetAttribute("xformOp:rotateXYZ")
            if not r_attr:
                r_attr = UsdGeom.Xformable(child).AddRotateXYZOp().GetAttr()
            rot = r_attr.Get() or Gf.Vec3f(0.0, 0.0, 0.0)
            # rx is the camera's PITCH and is preserved: the third-person
            # camera is pitched down 25 deg and levelling it on every episode
            # reset would be a different camera by the tenth episode.
            r_attr.Set(Gf.Vec3f(float(rot[0]), float(rot[1]),
                                yaw - _CAMERA_RZ_TO_HEADING_DEG))
            aimed.append(child.GetPath().pathString)
        report["cameras_aimed"] = aimed
        if not aimed:
            print(f"  ! no camera under {body_path} -- yaw turned the visible "
                  f"body but no view", flush=True)

        # The character's own offset is read off the rig rather than recalled,
        # because it is the one number here that a change to the asset would
        # invalidate without touching this file.
        rig = stage.GetPrimAtPath(f"{avatar_path}/character/rig")
        rig_yaw = _CHARACTER_YAW_DEG
        rig_rot = rig.GetAttribute("xformOp:rotateXYZ") if rig.IsValid() else None
        if rig_rot and rig_rot.Get() is not None:
            rig_yaw = float(rig_rot.Get()[2])
        built = (_ASSET_FACING_DEG + rig_yaw) % 360.0
        if abs((built - _DEFAULT_HEADING_DEG) % 360.0) > 0.5:
            print(
                f"  ! avatar rig faces {built:.1f} deg but the cameras are "
                f"aimed at {_DEFAULT_HEADING_DEG:.1f} deg -- the visible body "
                f"and the first-person view will disagree by "
                f"{(built - _DEFAULT_HEADING_DEG) % 360.0:.1f} deg",
                flush=True,
            )
        char_rotate_z = yaw - (_ASSET_FACING_DEG + rig_yaw)
        report["character_rotate_z_deg"] = char_rotate_z

    if char.IsValid():
        c_attr = char.GetAttribute("xformOp:translate")
        if not c_attr:
            c_attr = UsdGeom.Xformable(char).AddTranslateOp().GetAttr()
        c_attr.Set(target)
        if char_rotate_z is not None:
            r_attr = char.GetAttribute("xformOp:rotateXYZ")
            if not r_attr:
                # Appended, so xformOpOrder becomes [translate, rotateXYZ]:
                # USD applies the LAST op first, which is rotate-about-own-
                # origin then translate. The other order orbits the character
                # around the world origin.
                r_attr = UsdGeom.Xformable(char).AddRotateXYZOp().GetAttr()
            r_attr.Set(Gf.Vec3f(0.0, 0.0, float(char_rotate_z)))
        report["character_written"] = True
    else:
        print(
            f"  ! no character at {avatar_path}/character -- the capsule "
            f"moved but nothing visible did, and the capsule does not render",
            flush=True,
        )

    # --- and now the controller, if one can possibly be listening ------------
    if report["cct_extension_enabled"]:
        try:
            from omni.physxcct.scripts.ifaces import get_physx_cct_interface

            get_physx_cct_interface().set_position(body_path, (x_u, y_u, z_u))
            report["cct_set_position"] = "called"
            report["via_character_controller"] = True
        except Exception as exc:                             # noqa: BLE001
            # Not fatal: the USD write above already placed the capsule, and a
            # controller that is not registered for this path was never going
            # to overwrite it either.
            report["cct_set_position"] = f"failed: {exc!r}"

    if verbose:
        yaw_txt = "unchanged" if yaw_deg is None else f"{float(yaw_deg):.1f} deg"
        print(
            f"  avatar -> ({x_u * mpu:.3f}, {y_u * mpu:.3f}, {z_u * mpu:.3f}) m "
            f"yaw {yaw_txt}; cct={report['cct_set_position']}",
            flush=True,
        )
    return report


def _camera(stage: Usd.Stage, path: str, translate: Gf.Vec3d, *, pitch: float, focal: float) -> None:
    cam = UsdGeom.Camera.Define(stage, path)
    cam.AddTranslateOp().Set(translate)
    # A USD camera looks down its own -Z with +Y up. rotateXYZ = (90-pitch, 0,
    # -90*_FORWARD_X) turns that into "looks along the direction of travel,
    # world +Z up, pitched down by `pitch`".
    cam.AddRotateXYZOp().Set(Gf.Vec3f(90.0 - pitch, 0.0, -90.0 * _FORWARD_X))
    cam.CreateFocalLengthAttr(focal)
    # USD's default near plane is 1.0. In a warehouse that hides everything
    # within a metre of your face, which reads as "the camera is broken".
    cam.CreateClippingRangeAttr(Gf.Vec2f(0.01, 1_000_000.0))


def _worker_xy(stage: Usd.Stage) -> tuple[float, float]:
    """Where the warehouse's own Worker character stands, from a live stage.

    A human-shaped prop is already standing somewhere valid; borrowing its
    ground position is strictly better than inventing coordinates that might be
    inside a shelf. Falls back to the origin if the Worker is ever removed.
    """
    worker = stage.GetPrimAtPath(f"{ROOT}/Worker")
    if not worker.IsValid():
        print(f"  ! {ROOT}/Worker not found -- spawning at the origin instead", flush=True)
        return (0.0, 0.0)
    m = UsdGeom.XformCache().GetLocalToWorldTransform(worker)
    t = m.ExtractTranslation()
    return (float(t[0]), float(t[1]))


def read_base_facts(base: Path) -> dict:
    """Everything the build needs from the base stage, read from the LAYER.

    Deliberately Sdf-only: opening a *layer* reads a file, opening a *stage*
    composes 26,000 prims and 3,469 exact-triangle-mesh colliders, and the
    moment a physics extension is enabled against that, PhysX cooks every one
    of them. That cooking pass ran for over 13 minutes at 880% CPU and did not
    finish -- and the avatar layer does not need a single warehouse prim to be
    authored. So this reads the four facts it actually needs and never composes
    the warehouse at all.

    All four are authored in the base layer itself, not inside a payload --
    verified before relying on it.
    """
    layer = Sdf.Layer.FindOrOpen(str(base))
    if layer is None:
        raise RuntimeError(f"could not open base layer: {base}")

    # Layer metadata lives as info fields on the layer's pseudo-root prim spec.
    root = layer.pseudoRoot
    facts: dict = {
        "default_prim": layer.defaultPrim,
        "up_axis": root.GetInfo("upAxis") if root.HasInfo("upAxis") else None,
        "meters_per_unit": root.GetInfo("metersPerUnit") if root.HasInfo("metersPerUnit") else None,
        "worker_xy": None,
        "worker_asset": None,
        "gravity": None,
    }

    # Both are authored in the base's root layer (checked). If that ever stops
    # being true, fail loudly here rather than silently defaulting to USD's
    # Y-up / centimetres, which would put the avatar on its side at 1/100 scale.
    if facts["up_axis"] is None or facts["meters_per_unit"] is None:
        raise RuntimeError(
            f"{base.name} does not author upAxis/metersPerUnit in its root layer "
            f"(got {facts['up_axis']!r}/{facts['meters_per_unit']!r}); refusing to guess"
        )

    worker = layer.GetPrimAtPath(f"{ROOT}/Worker")
    if worker is not None and "xformOp:transform" in worker.properties:
        default = worker.properties["xformOp:transform"].default
        if default is not None:
            t = default.ExtractTranslation()
            facts["worker_xy"] = (float(t[0]), float(t[1]))
    # The character asset the avatar borrows its body from. Read from the arc
    # the stage already declares -- never typed out from memory (hard rule 1
    # is about prim paths, but an asset URL recalled wrongly fails the same
    # way: it resolves to nothing and the avatar is simply not there).
    if worker is not None:
        items = list(worker.payloadList.prependedItems) + list(worker.payloadList.appendedItems)
        refs = list(worker.referenceList.prependedItems) + list(worker.referenceList.appendedItems)
        for item in items + refs:
            if item.assetPath:
                facts["worker_asset"] = item.assetPath
                break

    scene = layer.GetPrimAtPath("/PhysicsScene")
    if scene is not None:
        facts["gravity"] = {
            k: (scene.properties[k].default if k in scene.properties else "<schema fallback>")
            for k in ("physics:gravityDirection", "physics:gravityMagnitude")
        }
    return facts


def _build_controls_graph(graph_path: str, body_path: str, *, speed: float) -> None:
    """Wire the shipped character-controller node to the avatar's capsule.

    The whole graph is three nodes because ``setupControls="Auto"`` makes the
    node bind WASD/E/Q and gamepad itself -- that is the "reuse existing
    wiring" the task asks for, and it lives in the USD, so the GUI session
    needs no script running: open the stage, press Play, walk.
    """
    # Not enabled by ANY shipped .kit experience -- checked across
    # /isaac-sim/apps/*.kit. Without it the node type is unregistered, and an
    # unregistered node type in a saved graph is a silent no-op.
    enable_extension("omni.physx.cct")

    # inputs:speed is typed `int` (units/s) in OgnCharacterController.ogn, and
    # this stage is 1.0 m/unit, so the finest control available is whole m/s.
    speed_i = max(1, int(round(float(speed))))
    if abs(speed_i - float(speed)) > 1e-6:
        print(
            f"  ! move_speed {speed} m/s -> {speed_i} m/s: the character "
            "controller node types speed as an int and the stage is in metres",
            flush=True,
        )

    # The character's follow is NOT in this graph, and that is a measured
    # decision rather than a preference. It used to be
    # OnTick -> ReadPrimAttribute -> WritePrimAttribute, correctly wired, and it
    # copied a constant: the character controller writes the capsule's pose to
    # USD, Fabric never receives it, and OmniGraph's ReadPrimAttribute reads
    # Fabric. Instrumented over 120 frames while the capsule travelled 2.58 m:
    # follow_tick computed 176 times, read_body 130 times, write_character 130
    # times, and read_body's outputs:value was byte-identical at every single
    # one. A graph that ticks, reads and writes, and does nothing.
    #
    # install_character_follow() does it in Python instead, which is also what
    # omni.physxcct's own first-person camera does to follow the same capsule --
    # a per-frame callback reading UsdGeom.XformCache. Shipped pattern, not a
    # local invention.
    keys = og.Controller.Keys
    og.Controller.edit(
        {"graph_path": graph_path, "evaluator_name": "execution"},
        {
            keys.CREATE_NODES: [
                ("on_play", "omni.graph.action.OnStageEvent"),
                ("on_stop", "omni.graph.action.OnStageEvent"),
                ("cct", "omni.physx.cct.OgnCharacterController"),
            ],
            keys.SET_VALUES: [
                ("on_play.inputs:eventName", "Simulation Start Play"),
                ("on_play.inputs:onlyPlayback", True),
                ("on_stop.inputs:eventName", "Simulation Stop Play"),
                ("on_stop.inputs:onlyPlayback", True),
                ("cct.inputs:capsulePath", body_path),
                ("cct.inputs:gravity", True),
                ("cct.inputs:speed", speed_i),
                ("cct.inputs:setupControls", "Auto"),
                # fpCameraPathToken deliberately unset: that mode hijacks the
                # active viewport and recentres the OS cursor every frame,
                # which is wrong over a livestream. The cameras are parented
                # instead, so switching view is rebinding the viewport.
            ],
            keys.CONNECT: [
                ("on_play.outputs:execOut", "cct.inputs:activate"),
                ("on_stop.outputs:execOut", "cct.inputs:deactivate"),
            ],
        },
    )


# ---------------------------------------------------------------------------
# Script entry point
# ---------------------------------------------------------------------------
def _attach_base_sublayer(out: Path, base: Path, facts: dict) -> None:
    """Turn the exported avatar-only layer into a layer that sublayers the base.

    Done with Sdf, on a layer, *after* everything is authored. Opening a layer
    reads a file; it does not compose a stage, so the warehouse is never built
    in this process and PhysX never sees a collider. Stage metadata does not
    compose across sublayers -- defaultPrim, upAxis and metersPerUnit are read
    from the root layer only -- so they are re-authored here from the base's
    own values.
    """
    layer = Sdf.Layer.FindOrOpen(str(out))
    if layer is None:
        raise RuntimeError(f"exported layer vanished: {out}")
    # Relative, so the pair of files stays portable between host and container.
    layer.subLayerPaths = [f"./{base.name}"]
    layer.defaultPrim = facts["default_prim"]
    layer.pseudoRoot.SetInfo("upAxis", facts["up_axis"])
    layer.pseudoRoot.SetInfo("metersPerUnit", facts["meters_per_unit"])
    layer.Save()


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path, default=OUT_STAGE)
    ap.add_argument("--base", type=Path, default=BASE_STAGE)
    ap.add_argument(
        "--spawn",
        default=None,
        help="ground position 'x,y'. Default: wherever the Worker stands.",
    )
    args = ap.parse_args(argv)

    if not args.base.exists():
        print(f"FAIL: base stage not found: {args.base}", flush=True)
        return 1

    print(f"base stage : {args.base}", flush=True)
    print(f"output     : {args.out}", flush=True)

    facts = read_base_facts(args.base)
    print(
        f"base facts : defaultPrim=/{facts['default_prim']} up={facts['up_axis']} "
        f"m/unit={facts['meters_per_unit']}",
        flush=True,
    )
    # Gravity in the wrong units makes the avatar fall at 100x, which reads as a
    # physics bug. Cheap to print, expensive to discover later.
    print(f"physics    : /PhysicsScene {facts['gravity']}", flush=True)

    cfg = load_avatar_config()
    if args.spawn:
        x, y = (float(v) for v in args.spawn.split(","))
        spawn_xy = (x, y)
    elif cfg.get("spawn_xy"):
        spawn_xy = tuple(float(v) for v in cfg["spawn_xy"])
        print(f"  spawn from config/scene.yaml: {spawn_xy}", flush=True)
    else:
        # Fallback only. Standing exactly where the Worker stands is safe but
        # opens the demo with two identical men in the same place.
        spawn_xy = facts["worker_xy"]
        if spawn_xy is None:
            print("  ! no Worker transform in the base layer -- spawning at origin", flush=True)
            spawn_xy = (0.0, 0.0)
    print(f"spawn      : {spawn_xy}", flush=True)
    print(f"character  : {facts['worker_asset']}", flush=True)
    if not facts["worker_asset"]:
        print("  ! /Root/Worker declares no asset -- avatar will have no visible body", flush=True)

    # An EMPTY stage, deliberately. See read_base_facts(): composing the
    # warehouse here and then enabling a physics extension puts PhysX into a
    # multi-minute cook of 3,469 triangle meshes for no benefit -- the avatar
    # layer references nothing in the warehouse. The base is attached as a
    # sublayer afterwards, at the Sdf level, where no composition happens.
    ctx = omni.usd.get_context()
    ctx.new_stage()
    for _ in range(10):
        _APP.update()
    stage = ctx.get_stage()
    if stage is None:
        print("FAIL: could not create a stage", flush=True)
        return 1

    UsdGeom.SetStageUpAxis(stage, facts["up_axis"])
    UsdGeom.SetStageMetersPerUnit(stage, facts["meters_per_unit"])
    # A "new stage" is not always empty -- whatever template Kit used would end
    # up authored into the avatar layer and composed over the warehouse.
    for prim in list(stage.GetPseudoRoot().GetChildren()):
        if prim.GetPath().pathString != ROOT:
            print(f"  dropping template prim {prim.GetPath()}", flush=True)
            stage.RemovePrim(prim.GetPath())
    UsdGeom.Xform.Define(stage, ROOT)

    paths = add_avatar(stage, spawn_xy=spawn_xy, worker_asset=facts["worker_asset"])

    for _ in range(5):
        _APP.update()

    if args.out.exists():
        args.out.unlink()
    stage.GetRootLayer().Export(str(args.out))
    _attach_base_sublayer(args.out, args.base, facts)

    print("\nbuilt:", flush=True)
    for k, v in paths.items():
        print(f"  {k:9s} {v}", flush=True)
    print(f"\nsaved {args.out} ({args.out.stat().st_size} bytes)", flush=True)
    print("Open THAT stage in the GUI, not observatory_base.usd.", flush=True)
    return 0


if __name__ == "__main__":
    code = main()
    # Do NOT hand the exit code to Kit's teardown. SimulationApp.close() races
    # with its own task group on this host and aborts with
    #   "Destroying busy TaskGroup!"  ->  Fatal Python error: Aborted
    # *after* the stage is authored, saved and closed -- turning a completely
    # successful build into exit 1. It is a SIGABRT, so it cannot be caught.
    # Everything this script produces is already on disk by now, so leave on
    # our own terms. A real failure still surfaces: an exception in main()
    # propagates and never reaches this line.
    sys.stdout.flush()
    sys.stderr.flush()
    os._exit(code)
